// Code generated by ent, DO NOT EDIT.

package tournamentadmin

import (
	"base-website/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.FieldLTE(FieldID, id))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v Role) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v Role) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...Role) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...Role) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.FieldNotIn(FieldRole, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.TournamentAdmin {
	return predicate.TournamentAdmin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTournament applies the HasEdge predicate on the "tournament" edge.
func HasTournament() predicate.TournamentAdmin {
	return predicate.TournamentAdmin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TournamentTable, TournamentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTournamentWith applies the HasEdge predicate on the "tournament" edge with a given conditions (other predicates).
func HasTournamentWith(preds ...predicate.Tournament) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(func(s *sql.Selector) {
		step := newTournamentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TournamentAdmin) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TournamentAdmin) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TournamentAdmin) predicate.TournamentAdmin {
	return predicate.TournamentAdmin(sql.NotPredicates(p))
}
