// Code generated by ent, DO NOT EDIT.

package rankgroup

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the rankgroup type in the database.
	Label = "rank_group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldRankMin holds the string denoting the rank_min field in the database.
	FieldRankMin = "rank_min"
	// FieldRankMax holds the string denoting the rank_max field in the database.
	FieldRankMax = "rank_max"
	// FieldPosition holds the string denoting the position field in the database.
	FieldPosition = "position"
	// EdgeTournament holds the string denoting the tournament edge name in mutations.
	EdgeTournament = "tournament"
	// EdgeTeams holds the string denoting the teams edge name in mutations.
	EdgeTeams = "teams"
	// Table holds the table name of the rankgroup in the database.
	Table = "rank_groups"
	// TournamentTable is the table that holds the tournament relation/edge.
	TournamentTable = "rank_groups"
	// TournamentInverseTable is the table name for the Tournament entity.
	// It exists in this package in order to avoid circular dependency with the "tournament" package.
	TournamentInverseTable = "tournaments"
	// TournamentColumn is the table column denoting the tournament relation/edge.
	TournamentColumn = "tournament_rank_groups"
	// TeamsTable is the table that holds the teams relation/edge.
	TeamsTable = "teams"
	// TeamsInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	TeamsInverseTable = "teams"
	// TeamsColumn is the table column denoting the teams relation/edge.
	TeamsColumn = "rank_group_teams"
)

// Columns holds all SQL columns for rankgroup fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldRankMin,
	FieldRankMax,
	FieldPosition,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "rank_groups"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"tournament_rank_groups",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the RankGroup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByRankMin orders the results by the rank_min field.
func ByRankMin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRankMin, opts...).ToFunc()
}

// ByRankMax orders the results by the rank_max field.
func ByRankMax(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRankMax, opts...).ToFunc()
}

// ByPosition orders the results by the position field.
func ByPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosition, opts...).ToFunc()
}

// ByTournamentField orders the results by tournament field.
func ByTournamentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTournamentStep(), sql.OrderByField(field, opts...))
	}
}

// ByTeamsCount orders the results by teams count.
func ByTeamsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTeamsStep(), opts...)
	}
}

// ByTeams orders the results by teams terms.
func ByTeams(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTournamentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TournamentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TournamentTable, TournamentColumn),
	)
}
func newTeamsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TeamsTable, TeamsColumn),
	)
}
