// Code generated by ent, DO NOT EDIT.

package rankgroup

import (
	"base-website/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldEQ(FieldName, v))
}

// RankMin applies equality check predicate on the "rank_min" field. It's identical to RankMinEQ.
func RankMin(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldEQ(FieldRankMin, v))
}

// RankMax applies equality check predicate on the "rank_max" field. It's identical to RankMaxEQ.
func RankMax(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldEQ(FieldRankMax, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldEQ(FieldPosition, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldContainsFold(FieldName, v))
}

// RankMinEQ applies the EQ predicate on the "rank_min" field.
func RankMinEQ(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldEQ(FieldRankMin, v))
}

// RankMinNEQ applies the NEQ predicate on the "rank_min" field.
func RankMinNEQ(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldNEQ(FieldRankMin, v))
}

// RankMinIn applies the In predicate on the "rank_min" field.
func RankMinIn(vs ...int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldIn(FieldRankMin, vs...))
}

// RankMinNotIn applies the NotIn predicate on the "rank_min" field.
func RankMinNotIn(vs ...int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldNotIn(FieldRankMin, vs...))
}

// RankMinGT applies the GT predicate on the "rank_min" field.
func RankMinGT(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldGT(FieldRankMin, v))
}

// RankMinGTE applies the GTE predicate on the "rank_min" field.
func RankMinGTE(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldGTE(FieldRankMin, v))
}

// RankMinLT applies the LT predicate on the "rank_min" field.
func RankMinLT(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldLT(FieldRankMin, v))
}

// RankMinLTE applies the LTE predicate on the "rank_min" field.
func RankMinLTE(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldLTE(FieldRankMin, v))
}

// RankMaxEQ applies the EQ predicate on the "rank_max" field.
func RankMaxEQ(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldEQ(FieldRankMax, v))
}

// RankMaxNEQ applies the NEQ predicate on the "rank_max" field.
func RankMaxNEQ(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldNEQ(FieldRankMax, v))
}

// RankMaxIn applies the In predicate on the "rank_max" field.
func RankMaxIn(vs ...int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldIn(FieldRankMax, vs...))
}

// RankMaxNotIn applies the NotIn predicate on the "rank_max" field.
func RankMaxNotIn(vs ...int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldNotIn(FieldRankMax, vs...))
}

// RankMaxGT applies the GT predicate on the "rank_max" field.
func RankMaxGT(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldGT(FieldRankMax, v))
}

// RankMaxGTE applies the GTE predicate on the "rank_max" field.
func RankMaxGTE(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldGTE(FieldRankMax, v))
}

// RankMaxLT applies the LT predicate on the "rank_max" field.
func RankMaxLT(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldLT(FieldRankMax, v))
}

// RankMaxLTE applies the LTE predicate on the "rank_max" field.
func RankMaxLTE(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldLTE(FieldRankMax, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.RankGroup {
	return predicate.RankGroup(sql.FieldLTE(FieldPosition, v))
}

// HasTournament applies the HasEdge predicate on the "tournament" edge.
func HasTournament() predicate.RankGroup {
	return predicate.RankGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TournamentTable, TournamentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTournamentWith applies the HasEdge predicate on the "tournament" edge with a given conditions (other predicates).
func HasTournamentWith(preds ...predicate.Tournament) predicate.RankGroup {
	return predicate.RankGroup(func(s *sql.Selector) {
		step := newTournamentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeams applies the HasEdge predicate on the "teams" edge.
func HasTeams() predicate.RankGroup {
	return predicate.RankGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TeamsTable, TeamsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamsWith applies the HasEdge predicate on the "teams" edge with a given conditions (other predicates).
func HasTeamsWith(preds ...predicate.Team) predicate.RankGroup {
	return predicate.RankGroup(func(s *sql.Selector) {
		step := newTeamsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RankGroup) predicate.RankGroup {
	return predicate.RankGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RankGroup) predicate.RankGroup {
	return predicate.RankGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RankGroup) predicate.RankGroup {
	return predicate.RankGroup(sql.NotPredicates(p))
}
