// Code generated by ent, DO NOT EDIT.

package team

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the team type in the database.
	Label = "team"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldImageURL holds the string denoting the image_url field in the database.
	FieldImageURL = "image_url"
	// FieldIsLocked holds the string denoting the is_locked field in the database.
	FieldIsLocked = "is_locked"
	// FieldIsRegistered holds the string denoting the is_registered field in the database.
	FieldIsRegistered = "is_registered"
	// FieldIsWaitlisted holds the string denoting the is_waitlisted field in the database.
	FieldIsWaitlisted = "is_waitlisted"
	// FieldWaitlistPosition holds the string denoting the waitlist_position field in the database.
	FieldWaitlistPosition = "waitlist_position"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldElo holds the string denoting the elo field in the database.
	FieldElo = "elo"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTournament holds the string denoting the tournament edge name in mutations.
	EdgeTournament = "tournament"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// EdgeMembers holds the string denoting the members edge name in mutations.
	EdgeMembers = "members"
	// EdgeRankGroup holds the string denoting the rank_group edge name in mutations.
	EdgeRankGroup = "rank_group"
	// EdgeInvitations holds the string denoting the invitations edge name in mutations.
	EdgeInvitations = "invitations"
	// Table holds the table name of the team in the database.
	Table = "teams"
	// TournamentTable is the table that holds the tournament relation/edge.
	TournamentTable = "teams"
	// TournamentInverseTable is the table name for the Tournament entity.
	// It exists in this package in order to avoid circular dependency with the "tournament" package.
	TournamentInverseTable = "tournaments"
	// TournamentColumn is the table column denoting the tournament relation/edge.
	TournamentColumn = "tournament_teams"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "teams"
	// CreatorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatorInverseTable = "users"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "user_created_teams"
	// MembersTable is the table that holds the members relation/edge.
	MembersTable = "team_members"
	// MembersInverseTable is the table name for the TeamMember entity.
	// It exists in this package in order to avoid circular dependency with the "teammember" package.
	MembersInverseTable = "team_members"
	// MembersColumn is the table column denoting the members relation/edge.
	MembersColumn = "team_members"
	// RankGroupTable is the table that holds the rank_group relation/edge.
	RankGroupTable = "teams"
	// RankGroupInverseTable is the table name for the RankGroup entity.
	// It exists in this package in order to avoid circular dependency with the "rankgroup" package.
	RankGroupInverseTable = "rank_groups"
	// RankGroupColumn is the table column denoting the rank_group relation/edge.
	RankGroupColumn = "rank_group_teams"
	// InvitationsTable is the table that holds the invitations relation/edge.
	InvitationsTable = "invitations"
	// InvitationsInverseTable is the table name for the Invitation entity.
	// It exists in this package in order to avoid circular dependency with the "invitation" package.
	InvitationsInverseTable = "invitations"
	// InvitationsColumn is the table column denoting the invitations relation/edge.
	InvitationsColumn = "team_invitations"
)

// Columns holds all SQL columns for team fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldImageURL,
	FieldIsLocked,
	FieldIsRegistered,
	FieldIsWaitlisted,
	FieldWaitlistPosition,
	FieldScore,
	FieldElo,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "teams"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"rank_group_teams",
	"tournament_teams",
	"user_created_teams",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsLocked holds the default value on creation for the "is_locked" field.
	DefaultIsLocked bool
	// DefaultIsRegistered holds the default value on creation for the "is_registered" field.
	DefaultIsRegistered bool
	// DefaultIsWaitlisted holds the default value on creation for the "is_waitlisted" field.
	DefaultIsWaitlisted bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Team queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByImageURL orders the results by the image_url field.
func ByImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageURL, opts...).ToFunc()
}

// ByIsLocked orders the results by the is_locked field.
func ByIsLocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsLocked, opts...).ToFunc()
}

// ByIsRegistered orders the results by the is_registered field.
func ByIsRegistered(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsRegistered, opts...).ToFunc()
}

// ByIsWaitlisted orders the results by the is_waitlisted field.
func ByIsWaitlisted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsWaitlisted, opts...).ToFunc()
}

// ByWaitlistPosition orders the results by the waitlist_position field.
func ByWaitlistPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWaitlistPosition, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByElo orders the results by the elo field.
func ByElo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldElo, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTournamentField orders the results by tournament field.
func ByTournamentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTournamentStep(), sql.OrderByField(field, opts...))
	}
}

// ByCreatorField orders the results by creator field.
func ByCreatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatorStep(), sql.OrderByField(field, opts...))
	}
}

// ByMembersCount orders the results by members count.
func ByMembersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMembersStep(), opts...)
	}
}

// ByMembers orders the results by members terms.
func ByMembers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMembersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRankGroupField orders the results by rank_group field.
func ByRankGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRankGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByInvitationsCount orders the results by invitations count.
func ByInvitationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInvitationsStep(), opts...)
	}
}

// ByInvitations orders the results by invitations terms.
func ByInvitations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInvitationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTournamentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TournamentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TournamentTable, TournamentColumn),
	)
}
func newCreatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
	)
}
func newMembersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MembersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
	)
}
func newRankGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RankGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RankGroupTable, RankGroupColumn),
	)
}
func newInvitationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InvitationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InvitationsTable, InvitationsColumn),
	)
}
