// Code generated by ent, DO NOT EDIT.

package tournament

import (
	"base-website/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldID, id))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldSlug, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldDescription, v))
}

// ImageURL applies equality check predicate on the "image_url" field. It's identical to ImageURLEQ.
func ImageURL(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldImageURL, v))
}

// IsVisible applies equality check predicate on the "is_visible" field. It's identical to IsVisibleEQ.
func IsVisible(v bool) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldIsVisible, v))
}

// RegistrationStart applies equality check predicate on the "registration_start" field. It's identical to RegistrationStartEQ.
func RegistrationStart(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldRegistrationStart, v))
}

// RegistrationEnd applies equality check predicate on the "registration_end" field. It's identical to RegistrationEndEQ.
func RegistrationEnd(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldRegistrationEnd, v))
}

// TournamentStart applies equality check predicate on the "tournament_start" field. It's identical to TournamentStartEQ.
func TournamentStart(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldTournamentStart, v))
}

// TournamentEnd applies equality check predicate on the "tournament_end" field. It's identical to TournamentEndEQ.
func TournamentEnd(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldTournamentEnd, v))
}

// MaxTeams applies equality check predicate on the "max_teams" field. It's identical to MaxTeamsEQ.
func MaxTeams(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldMaxTeams, v))
}

// CustomPageComponent applies equality check predicate on the "custom_page_component" field. It's identical to CustomPageComponentEQ.
func CustomPageComponent(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldCustomPageComponent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldUpdatedAt, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContainsFold(FieldSlug, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContainsFold(FieldDescription, v))
}

// ImageURLEQ applies the EQ predicate on the "image_url" field.
func ImageURLEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldImageURL, v))
}

// ImageURLNEQ applies the NEQ predicate on the "image_url" field.
func ImageURLNEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldImageURL, v))
}

// ImageURLIn applies the In predicate on the "image_url" field.
func ImageURLIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldImageURL, vs...))
}

// ImageURLNotIn applies the NotIn predicate on the "image_url" field.
func ImageURLNotIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldImageURL, vs...))
}

// ImageURLGT applies the GT predicate on the "image_url" field.
func ImageURLGT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldImageURL, v))
}

// ImageURLGTE applies the GTE predicate on the "image_url" field.
func ImageURLGTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldImageURL, v))
}

// ImageURLLT applies the LT predicate on the "image_url" field.
func ImageURLLT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldImageURL, v))
}

// ImageURLLTE applies the LTE predicate on the "image_url" field.
func ImageURLLTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldImageURL, v))
}

// ImageURLContains applies the Contains predicate on the "image_url" field.
func ImageURLContains(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContains(FieldImageURL, v))
}

// ImageURLHasPrefix applies the HasPrefix predicate on the "image_url" field.
func ImageURLHasPrefix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasPrefix(FieldImageURL, v))
}

// ImageURLHasSuffix applies the HasSuffix predicate on the "image_url" field.
func ImageURLHasSuffix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasSuffix(FieldImageURL, v))
}

// ImageURLIsNil applies the IsNil predicate on the "image_url" field.
func ImageURLIsNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldIsNull(FieldImageURL))
}

// ImageURLNotNil applies the NotNil predicate on the "image_url" field.
func ImageURLNotNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldNotNull(FieldImageURL))
}

// ImageURLEqualFold applies the EqualFold predicate on the "image_url" field.
func ImageURLEqualFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEqualFold(FieldImageURL, v))
}

// ImageURLContainsFold applies the ContainsFold predicate on the "image_url" field.
func ImageURLContainsFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContainsFold(FieldImageURL, v))
}

// IsVisibleEQ applies the EQ predicate on the "is_visible" field.
func IsVisibleEQ(v bool) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldIsVisible, v))
}

// IsVisibleNEQ applies the NEQ predicate on the "is_visible" field.
func IsVisibleNEQ(v bool) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldIsVisible, v))
}

// RegistrationStartEQ applies the EQ predicate on the "registration_start" field.
func RegistrationStartEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldRegistrationStart, v))
}

// RegistrationStartNEQ applies the NEQ predicate on the "registration_start" field.
func RegistrationStartNEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldRegistrationStart, v))
}

// RegistrationStartIn applies the In predicate on the "registration_start" field.
func RegistrationStartIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldRegistrationStart, vs...))
}

// RegistrationStartNotIn applies the NotIn predicate on the "registration_start" field.
func RegistrationStartNotIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldRegistrationStart, vs...))
}

// RegistrationStartGT applies the GT predicate on the "registration_start" field.
func RegistrationStartGT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldRegistrationStart, v))
}

// RegistrationStartGTE applies the GTE predicate on the "registration_start" field.
func RegistrationStartGTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldRegistrationStart, v))
}

// RegistrationStartLT applies the LT predicate on the "registration_start" field.
func RegistrationStartLT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldRegistrationStart, v))
}

// RegistrationStartLTE applies the LTE predicate on the "registration_start" field.
func RegistrationStartLTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldRegistrationStart, v))
}

// RegistrationEndEQ applies the EQ predicate on the "registration_end" field.
func RegistrationEndEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldRegistrationEnd, v))
}

// RegistrationEndNEQ applies the NEQ predicate on the "registration_end" field.
func RegistrationEndNEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldRegistrationEnd, v))
}

// RegistrationEndIn applies the In predicate on the "registration_end" field.
func RegistrationEndIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldRegistrationEnd, vs...))
}

// RegistrationEndNotIn applies the NotIn predicate on the "registration_end" field.
func RegistrationEndNotIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldRegistrationEnd, vs...))
}

// RegistrationEndGT applies the GT predicate on the "registration_end" field.
func RegistrationEndGT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldRegistrationEnd, v))
}

// RegistrationEndGTE applies the GTE predicate on the "registration_end" field.
func RegistrationEndGTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldRegistrationEnd, v))
}

// RegistrationEndLT applies the LT predicate on the "registration_end" field.
func RegistrationEndLT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldRegistrationEnd, v))
}

// RegistrationEndLTE applies the LTE predicate on the "registration_end" field.
func RegistrationEndLTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldRegistrationEnd, v))
}

// TournamentStartEQ applies the EQ predicate on the "tournament_start" field.
func TournamentStartEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldTournamentStart, v))
}

// TournamentStartNEQ applies the NEQ predicate on the "tournament_start" field.
func TournamentStartNEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldTournamentStart, v))
}

// TournamentStartIn applies the In predicate on the "tournament_start" field.
func TournamentStartIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldTournamentStart, vs...))
}

// TournamentStartNotIn applies the NotIn predicate on the "tournament_start" field.
func TournamentStartNotIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldTournamentStart, vs...))
}

// TournamentStartGT applies the GT predicate on the "tournament_start" field.
func TournamentStartGT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldTournamentStart, v))
}

// TournamentStartGTE applies the GTE predicate on the "tournament_start" field.
func TournamentStartGTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldTournamentStart, v))
}

// TournamentStartLT applies the LT predicate on the "tournament_start" field.
func TournamentStartLT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldTournamentStart, v))
}

// TournamentStartLTE applies the LTE predicate on the "tournament_start" field.
func TournamentStartLTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldTournamentStart, v))
}

// TournamentEndEQ applies the EQ predicate on the "tournament_end" field.
func TournamentEndEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldTournamentEnd, v))
}

// TournamentEndNEQ applies the NEQ predicate on the "tournament_end" field.
func TournamentEndNEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldTournamentEnd, v))
}

// TournamentEndIn applies the In predicate on the "tournament_end" field.
func TournamentEndIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldTournamentEnd, vs...))
}

// TournamentEndNotIn applies the NotIn predicate on the "tournament_end" field.
func TournamentEndNotIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldTournamentEnd, vs...))
}

// TournamentEndGT applies the GT predicate on the "tournament_end" field.
func TournamentEndGT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldTournamentEnd, v))
}

// TournamentEndGTE applies the GTE predicate on the "tournament_end" field.
func TournamentEndGTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldTournamentEnd, v))
}

// TournamentEndLT applies the LT predicate on the "tournament_end" field.
func TournamentEndLT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldTournamentEnd, v))
}

// TournamentEndLTE applies the LTE predicate on the "tournament_end" field.
func TournamentEndLTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldTournamentEnd, v))
}

// TournamentEndIsNil applies the IsNil predicate on the "tournament_end" field.
func TournamentEndIsNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldIsNull(FieldTournamentEnd))
}

// TournamentEndNotNil applies the NotNil predicate on the "tournament_end" field.
func TournamentEndNotNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldNotNull(FieldTournamentEnd))
}

// MaxTeamsEQ applies the EQ predicate on the "max_teams" field.
func MaxTeamsEQ(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldMaxTeams, v))
}

// MaxTeamsNEQ applies the NEQ predicate on the "max_teams" field.
func MaxTeamsNEQ(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldMaxTeams, v))
}

// MaxTeamsIn applies the In predicate on the "max_teams" field.
func MaxTeamsIn(vs ...int) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldMaxTeams, vs...))
}

// MaxTeamsNotIn applies the NotIn predicate on the "max_teams" field.
func MaxTeamsNotIn(vs ...int) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldMaxTeams, vs...))
}

// MaxTeamsGT applies the GT predicate on the "max_teams" field.
func MaxTeamsGT(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldMaxTeams, v))
}

// MaxTeamsGTE applies the GTE predicate on the "max_teams" field.
func MaxTeamsGTE(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldMaxTeams, v))
}

// MaxTeamsLT applies the LT predicate on the "max_teams" field.
func MaxTeamsLT(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldMaxTeams, v))
}

// MaxTeamsLTE applies the LTE predicate on the "max_teams" field.
func MaxTeamsLTE(v int) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldMaxTeams, v))
}

// TeamStructureIsNil applies the IsNil predicate on the "team_structure" field.
func TeamStructureIsNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldIsNull(FieldTeamStructure))
}

// TeamStructureNotNil applies the NotNil predicate on the "team_structure" field.
func TeamStructureNotNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldNotNull(FieldTeamStructure))
}

// CustomPageComponentEQ applies the EQ predicate on the "custom_page_component" field.
func CustomPageComponentEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldCustomPageComponent, v))
}

// CustomPageComponentNEQ applies the NEQ predicate on the "custom_page_component" field.
func CustomPageComponentNEQ(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldCustomPageComponent, v))
}

// CustomPageComponentIn applies the In predicate on the "custom_page_component" field.
func CustomPageComponentIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldCustomPageComponent, vs...))
}

// CustomPageComponentNotIn applies the NotIn predicate on the "custom_page_component" field.
func CustomPageComponentNotIn(vs ...string) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldCustomPageComponent, vs...))
}

// CustomPageComponentGT applies the GT predicate on the "custom_page_component" field.
func CustomPageComponentGT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldCustomPageComponent, v))
}

// CustomPageComponentGTE applies the GTE predicate on the "custom_page_component" field.
func CustomPageComponentGTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldCustomPageComponent, v))
}

// CustomPageComponentLT applies the LT predicate on the "custom_page_component" field.
func CustomPageComponentLT(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldCustomPageComponent, v))
}

// CustomPageComponentLTE applies the LTE predicate on the "custom_page_component" field.
func CustomPageComponentLTE(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldCustomPageComponent, v))
}

// CustomPageComponentContains applies the Contains predicate on the "custom_page_component" field.
func CustomPageComponentContains(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContains(FieldCustomPageComponent, v))
}

// CustomPageComponentHasPrefix applies the HasPrefix predicate on the "custom_page_component" field.
func CustomPageComponentHasPrefix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasPrefix(FieldCustomPageComponent, v))
}

// CustomPageComponentHasSuffix applies the HasSuffix predicate on the "custom_page_component" field.
func CustomPageComponentHasSuffix(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldHasSuffix(FieldCustomPageComponent, v))
}

// CustomPageComponentEqualFold applies the EqualFold predicate on the "custom_page_component" field.
func CustomPageComponentEqualFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldEqualFold(FieldCustomPageComponent, v))
}

// CustomPageComponentContainsFold applies the ContainsFold predicate on the "custom_page_component" field.
func CustomPageComponentContainsFold(v string) predicate.Tournament {
	return predicate.Tournament(sql.FieldContainsFold(FieldCustomPageComponent, v))
}

// ExternalLinksIsNil applies the IsNil predicate on the "external_links" field.
func ExternalLinksIsNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldIsNull(FieldExternalLinks))
}

// ExternalLinksNotNil applies the NotNil predicate on the "external_links" field.
func ExternalLinksNotNil() predicate.Tournament {
	return predicate.Tournament(sql.FieldNotNull(FieldExternalLinks))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Tournament {
	return predicate.Tournament(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.User) predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAdmins applies the HasEdge predicate on the "admins" edge.
func HasAdmins() predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AdminsTable, AdminsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAdminsWith applies the HasEdge predicate on the "admins" edge with a given conditions (other predicates).
func HasAdminsWith(preds ...predicate.TournamentAdmin) predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := newAdminsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeams applies the HasEdge predicate on the "teams" edge.
func HasTeams() predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TeamsTable, TeamsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamsWith applies the HasEdge predicate on the "teams" edge with a given conditions (other predicates).
func HasTeamsWith(preds ...predicate.Team) predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := newTeamsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRankGroups applies the HasEdge predicate on the "rank_groups" edge.
func HasRankGroups() predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RankGroupsTable, RankGroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRankGroupsWith applies the HasEdge predicate on the "rank_groups" edge with a given conditions (other predicates).
func HasRankGroupsWith(preds ...predicate.RankGroup) predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := newRankGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeamMembers applies the HasEdge predicate on the "team_members" edge.
func HasTeamMembers() predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TeamMembersTable, TeamMembersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamMembersWith applies the HasEdge predicate on the "team_members" edge with a given conditions (other predicates).
func HasTeamMembersWith(preds ...predicate.TeamMember) predicate.Tournament {
	return predicate.Tournament(func(s *sql.Selector) {
		step := newTeamMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Tournament) predicate.Tournament {
	return predicate.Tournament(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Tournament) predicate.Tournament {
	return predicate.Tournament(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Tournament) predicate.Tournament {
	return predicate.Tournament(sql.NotPredicates(p))
}
