// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppsColumns holds the columns for the "apps" table.
	AppsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "secret", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "redirect_uris", Type: field.TypeJSON},
		{Name: "implicit_consent", Type: field.TypeBool},
		{Name: "description", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "roles", Type: field.TypeJSON},
		{Name: "owner_id", Type: field.TypeInt},
	}
	// AppsTable holds the schema information for the "apps" table.
	AppsTable = &schema.Table{
		Name:       "apps",
		Columns:    AppsColumns,
		PrimaryKey: []*schema.Column{AppsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "apps_users_apps",
				Columns:    []*schema.Column{AppsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// AuthCodesColumns holds the columns for the "auth_codes" table.
	AuthCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "auth_request_id", Type: field.TypeString},
		{Name: "expiration", Type: field.TypeTime},
	}
	// AuthCodesTable holds the schema information for the "auth_codes" table.
	AuthCodesTable = &schema.Table{
		Name:       "auth_codes",
		Columns:    AuthCodesColumns,
		PrimaryKey: []*schema.Column{AuthCodesColumns[0]},
	}
	// AuthRefreshTokensColumns holds the columns for the "auth_refresh_tokens" table.
	AuthRefreshTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "token", Type: field.TypeString},
		{Name: "subject", Type: field.TypeString},
		{Name: "auth_time", Type: field.TypeTime},
		{Name: "amr", Type: field.TypeJSON},
		{Name: "audience", Type: field.TypeJSON},
		{Name: "user_id", Type: field.TypeString},
		{Name: "application_id", Type: field.TypeString},
		{Name: "expiration", Type: field.TypeTime},
		{Name: "scopes", Type: field.TypeJSON},
	}
	// AuthRefreshTokensTable holds the schema information for the "auth_refresh_tokens" table.
	AuthRefreshTokensTable = &schema.Table{
		Name:       "auth_refresh_tokens",
		Columns:    AuthRefreshTokensColumns,
		PrimaryKey: []*schema.Column{AuthRefreshTokensColumns[0]},
	}
	// AuthTokensColumns holds the columns for the "auth_tokens" table.
	AuthTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "application_id", Type: field.TypeString},
		{Name: "subject", Type: field.TypeString},
		{Name: "refresh_token_id", Type: field.TypeString},
		{Name: "audience", Type: field.TypeJSON},
		{Name: "expiration", Type: field.TypeTime},
		{Name: "scopes", Type: field.TypeJSON},
	}
	// AuthTokensTable holds the schema information for the "auth_tokens" table.
	AuthTokensTable = &schema.Table{
		Name:       "auth_tokens",
		Columns:    AuthTokensColumns,
		PrimaryKey: []*schema.Column{AuthTokensColumns[0]},
	}
	// ComponentsColumns holds the columns for the "components" table.
	ComponentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "image_url", Type: field.TypeString, Default: "components/default.png"},
		{Name: "color", Type: field.TypeString, Nullable: true},
		{Name: "vote_components", Type: field.TypeInt},
	}
	// ComponentsTable holds the schema information for the "components" table.
	ComponentsTable = &schema.Table{
		Name:       "components",
		Columns:    ComponentsColumns,
		PrimaryKey: []*schema.Column{ComponentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "components_votes_components",
				Columns:    []*schema.Column{ComponentsColumns[5]},
				RefColumns: []*schema.Column{VotesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ConsentsColumns holds the columns for the "consents" table.
	ConsentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "scopes", Type: field.TypeJSON},
		{Name: "expiration_date", Type: field.TypeTime},
		{Name: "application_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeInt},
	}
	// ConsentsTable holds the schema information for the "consents" table.
	ConsentsTable = &schema.Table{
		Name:       "consents",
		Columns:    ConsentsColumns,
		PrimaryKey: []*schema.Column{ConsentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "consents_apps_consents",
				Columns:    []*schema.Column{ConsentsColumns[5]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "consents_users_consents",
				Columns:    []*schema.Column{ConsentsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// InvitationsColumns holds the columns for the "invitations" table.
	InvitationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "ACCEPTED", "DECLINED", "EXPIRED", "REVOKED"}, Default: "PENDING"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "message", Type: field.TypeString, Nullable: true},
		{Name: "team_invitations", Type: field.TypeInt},
		{Name: "user_received_invitations", Type: field.TypeInt},
	}
	// InvitationsTable holds the schema information for the "invitations" table.
	InvitationsTable = &schema.Table{
		Name:       "invitations",
		Columns:    InvitationsColumns,
		PrimaryKey: []*schema.Column{InvitationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invitations_teams_invitations",
				Columns:    []*schema.Column{InvitationsColumns[5]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "invitations_users_received_invitations",
				Columns:    []*schema.Column{InvitationsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RankGroupsColumns holds the columns for the "rank_groups" table.
	RankGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "rank_min", Type: field.TypeInt},
		{Name: "rank_max", Type: field.TypeInt},
		{Name: "tournament_rank_groups", Type: field.TypeInt},
	}
	// RankGroupsTable holds the schema information for the "rank_groups" table.
	RankGroupsTable = &schema.Table{
		Name:       "rank_groups",
		Columns:    RankGroupsColumns,
		PrimaryKey: []*schema.Column{RankGroupsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rank_groups_tournaments_rank_groups",
				Columns:    []*schema.Column{RankGroupsColumns[4]},
				RefColumns: []*schema.Column{TournamentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TeamsColumns holds the columns for the "teams" table.
	TeamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "image_url", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"DRAFT", "LOCKED", "CONFIRMED", "WAITING", "DISQUALIFIED"}, Default: "DRAFT"},
		{Name: "is_locked", Type: field.TypeBool, Default: false},
		{Name: "queue_position", Type: field.TypeInt, Nullable: true},
		{Name: "score", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "team_rank_group", Type: field.TypeInt, Nullable: true},
		{Name: "tournament_teams", Type: field.TypeInt},
		{Name: "user_created_teams", Type: field.TypeInt},
	}
	// TeamsTable holds the schema information for the "teams" table.
	TeamsTable = &schema.Table{
		Name:       "teams",
		Columns:    TeamsColumns,
		PrimaryKey: []*schema.Column{TeamsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "teams_rank_groups_rank_group",
				Columns:    []*schema.Column{TeamsColumns[8]},
				RefColumns: []*schema.Column{RankGroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "teams_tournaments_teams",
				Columns:    []*schema.Column{TeamsColumns[9]},
				RefColumns: []*schema.Column{TournamentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "teams_users_created_teams",
				Columns:    []*schema.Column{TeamsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TeamMembersColumns holds the columns for the "team_members" table.
	TeamMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "role", Type: field.TypeString},
		{Name: "team_members", Type: field.TypeInt},
		{Name: "user_team_memberships", Type: field.TypeInt},
	}
	// TeamMembersTable holds the schema information for the "team_members" table.
	TeamMembersTable = &schema.Table{
		Name:       "team_members",
		Columns:    TeamMembersColumns,
		PrimaryKey: []*schema.Column{TeamMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "team_members_teams_members",
				Columns:    []*schema.Column{TeamMembersColumns[2]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "team_members_users_team_memberships",
				Columns:    []*schema.Column{TeamMembersColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TournamentsColumns holds the columns for the "tournaments" table.
	TournamentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "is_visible", Type: field.TypeBool, Default: false},
		{Name: "registration_start", Type: field.TypeTime},
		{Name: "registration_end", Type: field.TypeTime},
		{Name: "tournament_start", Type: field.TypeTime},
		{Name: "tournament_end", Type: field.TypeTime, Nullable: true},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"DRAFT", "REGISTRATION_OPEN", "REGISTRATION_CLOSED", "ONGOING", "FINISHED"}, Default: "DRAFT"},
		{Name: "max_teams", Type: field.TypeInt},
		{Name: "team_structure", Type: field.TypeJSON, Nullable: true},
		{Name: "custom_page_component", Type: field.TypeString, Default: "default"},
		{Name: "external_link", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_created_tournaments", Type: field.TypeInt},
	}
	// TournamentsTable holds the schema information for the "tournaments" table.
	TournamentsTable = &schema.Table{
		Name:       "tournaments",
		Columns:    TournamentsColumns,
		PrimaryKey: []*schema.Column{TournamentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tournaments_users_created_tournaments",
				Columns:    []*schema.Column{TournamentsColumns[15]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TournamentAdminsColumns holds the columns for the "tournament_admins" table.
	TournamentAdminsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"CREATOR", "SUPER_ADMIN", "ADMIN"}, Default: "ADMIN"},
		{Name: "tournament_admins", Type: field.TypeInt},
		{Name: "user_tournament_admin_roles", Type: field.TypeInt},
	}
	// TournamentAdminsTable holds the schema information for the "tournament_admins" table.
	TournamentAdminsTable = &schema.Table{
		Name:       "tournament_admins",
		Columns:    TournamentAdminsColumns,
		PrimaryKey: []*schema.Column{TournamentAdminsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tournament_admins_tournaments_admins",
				Columns:    []*schema.Column{TournamentAdminsColumns[2]},
				RefColumns: []*schema.Column{TournamentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "tournament_admins_users_tournament_admin_roles",
				Columns:    []*schema.Column{TournamentAdminsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "picture", Type: field.TypeString, Nullable: true},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"user", "admin"}, Default: "user"},
		{Name: "roles", Type: field.TypeJSON},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserVotesColumns holds the columns for the "user_votes" table.
	UserVotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "component_user_votes", Type: field.TypeInt},
		{Name: "user_user_votes", Type: field.TypeInt},
	}
	// UserVotesTable holds the schema information for the "user_votes" table.
	UserVotesTable = &schema.Table{
		Name:       "user_votes",
		Columns:    UserVotesColumns,
		PrimaryKey: []*schema.Column{UserVotesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_votes_components_user_votes",
				Columns:    []*schema.Column{UserVotesColumns[2]},
				RefColumns: []*schema.Column{ComponentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_votes_users_user_votes",
				Columns:    []*schema.Column{UserVotesColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// VotesColumns holds the columns for the "votes" table.
	VotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "visible", Type: field.TypeBool, Default: false},
		{Name: "start_at", Type: field.TypeTime},
		{Name: "end_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_created_votes", Type: field.TypeInt},
	}
	// VotesTable holds the schema information for the "votes" table.
	VotesTable = &schema.Table{
		Name:       "votes",
		Columns:    VotesColumns,
		PrimaryKey: []*schema.Column{VotesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "votes_users_created_votes",
				Columns:    []*schema.Column{VotesColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppsTable,
		AuthCodesTable,
		AuthRefreshTokensTable,
		AuthTokensTable,
		ComponentsTable,
		ConsentsTable,
		InvitationsTable,
		RankGroupsTable,
		TeamsTable,
		TeamMembersTable,
		TournamentsTable,
		TournamentAdminsTable,
		UsersTable,
		UserVotesTable,
		VotesTable,
	}
)

func init() {
	AppsTable.ForeignKeys[0].RefTable = UsersTable
	ComponentsTable.ForeignKeys[0].RefTable = VotesTable
	ConsentsTable.ForeignKeys[0].RefTable = AppsTable
	ConsentsTable.ForeignKeys[1].RefTable = UsersTable
	InvitationsTable.ForeignKeys[0].RefTable = TeamsTable
	InvitationsTable.ForeignKeys[1].RefTable = UsersTable
	RankGroupsTable.ForeignKeys[0].RefTable = TournamentsTable
	TeamsTable.ForeignKeys[0].RefTable = RankGroupsTable
	TeamsTable.ForeignKeys[1].RefTable = TournamentsTable
	TeamsTable.ForeignKeys[2].RefTable = UsersTable
	TeamMembersTable.ForeignKeys[0].RefTable = TeamsTable
	TeamMembersTable.ForeignKeys[1].RefTable = UsersTable
	TournamentsTable.ForeignKeys[0].RefTable = UsersTable
	TournamentAdminsTable.ForeignKeys[0].RefTable = TournamentsTable
	TournamentAdminsTable.ForeignKeys[1].RefTable = UsersTable
	UserVotesTable.ForeignKeys[0].RefTable = ComponentsTable
	UserVotesTable.ForeignKeys[1].RefTable = UsersTable
	VotesTable.ForeignKeys[0].RefTable = UsersTable
}
