// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-website/ent/authcode"
	"base-website/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthCodeUpdate is the builder for updating AuthCode entities.
type AuthCodeUpdate struct {
	config
	hooks    []Hook
	mutation *AuthCodeMutation
}

// Where appends a list predicates to the AuthCodeUpdate builder.
func (_u *AuthCodeUpdate) Where(ps ...predicate.AuthCode) *AuthCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAuthRequestID sets the "auth_request_id" field.
func (_u *AuthCodeUpdate) SetAuthRequestID(v string) *AuthCodeUpdate {
	_u.mutation.SetAuthRequestID(v)
	return _u
}

// SetNillableAuthRequestID sets the "auth_request_id" field if the given value is not nil.
func (_u *AuthCodeUpdate) SetNillableAuthRequestID(v *string) *AuthCodeUpdate {
	if v != nil {
		_u.SetAuthRequestID(*v)
	}
	return _u
}

// SetExpiration sets the "expiration" field.
func (_u *AuthCodeUpdate) SetExpiration(v time.Time) *AuthCodeUpdate {
	_u.mutation.SetExpiration(v)
	return _u
}

// SetNillableExpiration sets the "expiration" field if the given value is not nil.
func (_u *AuthCodeUpdate) SetNillableExpiration(v *time.Time) *AuthCodeUpdate {
	if v != nil {
		_u.SetExpiration(*v)
	}
	return _u
}

// Mutation returns the AuthCodeMutation object of the builder.
func (_u *AuthCodeUpdate) Mutation() *AuthCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(authcode.Table, authcode.Columns, sqlgraph.NewFieldSpec(authcode.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AuthRequestID(); ok {
		_spec.SetField(authcode.FieldAuthRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Expiration(); ok {
		_spec.SetField(authcode.FieldExpiration, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthCodeUpdateOne is the builder for updating a single AuthCode entity.
type AuthCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthCodeMutation
}

// SetAuthRequestID sets the "auth_request_id" field.
func (_u *AuthCodeUpdateOne) SetAuthRequestID(v string) *AuthCodeUpdateOne {
	_u.mutation.SetAuthRequestID(v)
	return _u
}

// SetNillableAuthRequestID sets the "auth_request_id" field if the given value is not nil.
func (_u *AuthCodeUpdateOne) SetNillableAuthRequestID(v *string) *AuthCodeUpdateOne {
	if v != nil {
		_u.SetAuthRequestID(*v)
	}
	return _u
}

// SetExpiration sets the "expiration" field.
func (_u *AuthCodeUpdateOne) SetExpiration(v time.Time) *AuthCodeUpdateOne {
	_u.mutation.SetExpiration(v)
	return _u
}

// SetNillableExpiration sets the "expiration" field if the given value is not nil.
func (_u *AuthCodeUpdateOne) SetNillableExpiration(v *time.Time) *AuthCodeUpdateOne {
	if v != nil {
		_u.SetExpiration(*v)
	}
	return _u
}

// Mutation returns the AuthCodeMutation object of the builder.
func (_u *AuthCodeUpdateOne) Mutation() *AuthCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthCodeUpdate builder.
func (_u *AuthCodeUpdateOne) Where(ps ...predicate.AuthCode) *AuthCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthCodeUpdateOne) Select(field string, fields ...string) *AuthCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthCode entity.
func (_u *AuthCodeUpdateOne) Save(ctx context.Context) (*AuthCode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthCodeUpdateOne) SaveX(ctx context.Context) *AuthCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthCodeUpdateOne) sqlSave(ctx context.Context) (_node *AuthCode, err error) {
	_spec := sqlgraph.NewUpdateSpec(authcode.Table, authcode.Columns, sqlgraph.NewFieldSpec(authcode.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authcode.FieldID)
		for _, f := range fields {
			if !authcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AuthRequestID(); ok {
		_spec.SetField(authcode.FieldAuthRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Expiration(); ok {
		_spec.SetField(authcode.FieldExpiration, field.TypeTime, value)
	}
	_node = &AuthCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
