// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-website/ent/rankgroup"
	"base-website/ent/tournament"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// RankGroup is the model entity for the RankGroup schema.
type RankGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// RankMin holds the value of the "rank_min" field.
	RankMin int `json:"rank_min,omitempty"`
	// RankMax holds the value of the "rank_max" field.
	RankMax int `json:"rank_max,omitempty"`
	// Position holds the value of the "position" field.
	Position int `json:"position,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RankGroupQuery when eager-loading is set.
	Edges                 RankGroupEdges `json:"edges"`
	rank_group_tournament *int
	selectValues          sql.SelectValues
}

// RankGroupEdges holds the relations/edges for other nodes in the graph.
type RankGroupEdges struct {
	// Tournament holds the value of the tournament edge.
	Tournament *Tournament `json:"tournament,omitempty"`
	// Teams holds the value of the teams edge.
	Teams []*Team `json:"teams,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TournamentOrErr returns the Tournament value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RankGroupEdges) TournamentOrErr() (*Tournament, error) {
	if e.Tournament != nil {
		return e.Tournament, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tournament.Label}
	}
	return nil, &NotLoadedError{edge: "tournament"}
}

// TeamsOrErr returns the Teams value or an error if the edge
// was not loaded in eager-loading.
func (e RankGroupEdges) TeamsOrErr() ([]*Team, error) {
	if e.loadedTypes[1] {
		return e.Teams, nil
	}
	return nil, &NotLoadedError{edge: "teams"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RankGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rankgroup.FieldID, rankgroup.FieldRankMin, rankgroup.FieldRankMax, rankgroup.FieldPosition:
			values[i] = new(sql.NullInt64)
		case rankgroup.FieldName:
			values[i] = new(sql.NullString)
		case rankgroup.ForeignKeys[0]: // rank_group_tournament
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RankGroup fields.
func (_m *RankGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rankgroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case rankgroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case rankgroup.FieldRankMin:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rank_min", values[i])
			} else if value.Valid {
				_m.RankMin = int(value.Int64)
			}
		case rankgroup.FieldRankMax:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rank_max", values[i])
			} else if value.Valid {
				_m.RankMax = int(value.Int64)
			}
		case rankgroup.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		case rankgroup.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field rank_group_tournament", value)
			} else if value.Valid {
				_m.rank_group_tournament = new(int)
				*_m.rank_group_tournament = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RankGroup.
// This includes values selected through modifiers, order, etc.
func (_m *RankGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTournament queries the "tournament" edge of the RankGroup entity.
func (_m *RankGroup) QueryTournament() *TournamentQuery {
	return NewRankGroupClient(_m.config).QueryTournament(_m)
}

// QueryTeams queries the "teams" edge of the RankGroup entity.
func (_m *RankGroup) QueryTeams() *TeamQuery {
	return NewRankGroupClient(_m.config).QueryTeams(_m)
}

// Update returns a builder for updating this RankGroup.
// Note that you need to call RankGroup.Unwrap() before calling this method if this RankGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RankGroup) Update() *RankGroupUpdateOne {
	return NewRankGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RankGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RankGroup) Unwrap() *RankGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RankGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RankGroup) String() string {
	var builder strings.Builder
	builder.WriteString("RankGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("rank_min=")
	builder.WriteString(fmt.Sprintf("%v", _m.RankMin))
	builder.WriteString(", ")
	builder.WriteString("rank_max=")
	builder.WriteString(fmt.Sprintf("%v", _m.RankMax))
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteByte(')')
	return builder.String()
}

// RankGroups is a parsable slice of RankGroup.
type RankGroups []*RankGroup
