// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-website/ent/rankgroup"
	"base-website/ent/team"
	"base-website/ent/tournament"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RankGroupCreate is the builder for creating a RankGroup entity.
type RankGroupCreate struct {
	config
	mutation *RankGroupMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *RankGroupCreate) SetName(v string) *RankGroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRankMin sets the "rank_min" field.
func (_c *RankGroupCreate) SetRankMin(v int) *RankGroupCreate {
	_c.mutation.SetRankMin(v)
	return _c
}

// SetRankMax sets the "rank_max" field.
func (_c *RankGroupCreate) SetRankMax(v int) *RankGroupCreate {
	_c.mutation.SetRankMax(v)
	return _c
}

// SetPosition sets the "position" field.
func (_c *RankGroupCreate) SetPosition(v int) *RankGroupCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetTournamentID sets the "tournament" edge to the Tournament entity by ID.
func (_c *RankGroupCreate) SetTournamentID(id int) *RankGroupCreate {
	_c.mutation.SetTournamentID(id)
	return _c
}

// SetTournament sets the "tournament" edge to the Tournament entity.
func (_c *RankGroupCreate) SetTournament(v *Tournament) *RankGroupCreate {
	return _c.SetTournamentID(v.ID)
}

// AddTeamIDs adds the "teams" edge to the Team entity by IDs.
func (_c *RankGroupCreate) AddTeamIDs(ids ...int) *RankGroupCreate {
	_c.mutation.AddTeamIDs(ids...)
	return _c
}

// AddTeams adds the "teams" edges to the Team entity.
func (_c *RankGroupCreate) AddTeams(v ...*Team) *RankGroupCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeamIDs(ids...)
}

// Mutation returns the RankGroupMutation object of the builder.
func (_c *RankGroupCreate) Mutation() *RankGroupMutation {
	return _c.mutation
}

// Save creates the RankGroup in the database.
func (_c *RankGroupCreate) Save(ctx context.Context) (*RankGroup, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RankGroupCreate) SaveX(ctx context.Context) *RankGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RankGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RankGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RankGroupCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RankGroup.name"`)}
	}
	if _, ok := _c.mutation.RankMin(); !ok {
		return &ValidationError{Name: "rank_min", err: errors.New(`ent: missing required field "RankGroup.rank_min"`)}
	}
	if _, ok := _c.mutation.RankMax(); !ok {
		return &ValidationError{Name: "rank_max", err: errors.New(`ent: missing required field "RankGroup.rank_max"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "RankGroup.position"`)}
	}
	if len(_c.mutation.TournamentIDs()) == 0 {
		return &ValidationError{Name: "tournament", err: errors.New(`ent: missing required edge "RankGroup.tournament"`)}
	}
	return nil
}

func (_c *RankGroupCreate) sqlSave(ctx context.Context) (*RankGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RankGroupCreate) createSpec() (*RankGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &RankGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rankgroup.Table, sqlgraph.NewFieldSpec(rankgroup.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(rankgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.RankMin(); ok {
		_spec.SetField(rankgroup.FieldRankMin, field.TypeInt, value)
		_node.RankMin = value
	}
	if value, ok := _c.mutation.RankMax(); ok {
		_spec.SetField(rankgroup.FieldRankMax, field.TypeInt, value)
		_node.RankMax = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(rankgroup.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if nodes := _c.mutation.TournamentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rankgroup.TournamentTable,
			Columns: []string{rankgroup.TournamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.rank_group_tournament = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   rankgroup.TeamsTable,
			Columns: []string{rankgroup.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RankGroupCreateBulk is the builder for creating many RankGroup entities in bulk.
type RankGroupCreateBulk struct {
	config
	err      error
	builders []*RankGroupCreate
}

// Save creates the RankGroup entities in the database.
func (_c *RankGroupCreateBulk) Save(ctx context.Context) ([]*RankGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RankGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RankGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RankGroupCreateBulk) SaveX(ctx context.Context) []*RankGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RankGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RankGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
