// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-website/ent/app"
	"base-website/ent/authcode"
	"base-website/ent/component"
	"base-website/ent/consent"
	"base-website/ent/schema"
	"base-website/ent/user"
	"base-website/ent/uservote"
	"base-website/ent/vote"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescCreatedAt is the schema descriptor for created_at field.
	appDescCreatedAt := appFields[6].Descriptor()
	// app.DefaultCreatedAt holds the default value on creation for the created_at field.
	app.DefaultCreatedAt = appDescCreatedAt.Default.(func() time.Time)
	// appDescUpdatedAt is the schema descriptor for updated_at field.
	appDescUpdatedAt := appFields[7].Descriptor()
	// app.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	app.DefaultUpdatedAt = appDescUpdatedAt.Default.(func() time.Time)
	// app.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	app.UpdateDefaultUpdatedAt = appDescUpdatedAt.UpdateDefault.(func() time.Time)
	// appDescRoles is the schema descriptor for roles field.
	appDescRoles := appFields[10].Descriptor()
	// app.DefaultRoles holds the default value on creation for the roles field.
	app.DefaultRoles = appDescRoles.Default.([]string)
	authcodeFields := schema.AuthCode{}.Fields()
	_ = authcodeFields
	// authcodeDescExpiration is the schema descriptor for expiration field.
	authcodeDescExpiration := authcodeFields[2].Descriptor()
	// authcode.DefaultExpiration holds the default value on creation for the expiration field.
	authcode.DefaultExpiration = authcodeDescExpiration.Default.(func() time.Time)
	componentFields := schema.Component{}.Fields()
	_ = componentFields
	// componentDescImageURL is the schema descriptor for image_url field.
	componentDescImageURL := componentFields[2].Descriptor()
	// component.DefaultImageURL holds the default value on creation for the image_url field.
	component.DefaultImageURL = componentDescImageURL.Default.(string)
	consentFields := schema.Consent{}.Fields()
	_ = consentFields
	// consentDescCreatedAt is the schema descriptor for created_at field.
	consentDescCreatedAt := consentFields[1].Descriptor()
	// consent.DefaultCreatedAt holds the default value on creation for the created_at field.
	consent.DefaultCreatedAt = consentDescCreatedAt.Default.(func() time.Time)
	// consentDescUpdatedAt is the schema descriptor for updated_at field.
	consentDescUpdatedAt := consentFields[2].Descriptor()
	// consent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	consent.DefaultUpdatedAt = consentDescUpdatedAt.Default.(func() time.Time)
	// consent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	consent.UpdateDefaultUpdatedAt = consentDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescRoles is the schema descriptor for roles field.
	userDescRoles := userFields[11].Descriptor()
	// user.DefaultRoles holds the default value on creation for the roles field.
	user.DefaultRoles = userDescRoles.Default.([]string)
	uservoteFields := schema.UserVote{}.Fields()
	_ = uservoteFields
	// uservoteDescCreatedAt is the schema descriptor for created_at field.
	uservoteDescCreatedAt := uservoteFields[0].Descriptor()
	// uservote.DefaultCreatedAt holds the default value on creation for the created_at field.
	uservote.DefaultCreatedAt = uservoteDescCreatedAt.Default.(func() time.Time)
	voteFields := schema.Vote{}.Fields()
	_ = voteFields
	// voteDescVisible is the schema descriptor for visible field.
	voteDescVisible := voteFields[2].Descriptor()
	// vote.DefaultVisible holds the default value on creation for the visible field.
	vote.DefaultVisible = voteDescVisible.Default.(bool)
	// voteDescCreatedAt is the schema descriptor for created_at field.
	voteDescCreatedAt := voteFields[5].Descriptor()
	// vote.DefaultCreatedAt holds the default value on creation for the created_at field.
	vote.DefaultCreatedAt = voteDescCreatedAt.Default.(func() time.Time)
	// voteDescUpdatedAt is the schema descriptor for updated_at field.
	voteDescUpdatedAt := voteFields[6].Descriptor()
	// vote.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vote.DefaultUpdatedAt = voteDescUpdatedAt.Default.(func() time.Time)
	// vote.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vote.UpdateDefaultUpdatedAt = voteDescUpdatedAt.UpdateDefault.(func() time.Time)
}
