// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-website/ent/invitation"
	"base-website/ent/predicate"
	"base-website/ent/rankgroup"
	"base-website/ent/team"
	"base-website/ent/teammember"
	"base-website/ent/tournament"
	"base-website/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TeamUpdate is the builder for updating Team entities.
type TeamUpdate struct {
	config
	hooks    []Hook
	mutation *TeamMutation
}

// Where appends a list predicates to the TeamUpdate builder.
func (_u *TeamUpdate) Where(ps ...predicate.Team) *TeamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TeamUpdate) SetName(v string) *TeamUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableName(v *string) *TeamUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *TeamUpdate) SetImageURL(v string) *TeamUpdate {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableImageURL(v *string) *TeamUpdate {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// ClearImageURL clears the value of the "image_url" field.
func (_u *TeamUpdate) ClearImageURL() *TeamUpdate {
	_u.mutation.ClearImageURL()
	return _u
}

// SetIsLocked sets the "is_locked" field.
func (_u *TeamUpdate) SetIsLocked(v bool) *TeamUpdate {
	_u.mutation.SetIsLocked(v)
	return _u
}

// SetNillableIsLocked sets the "is_locked" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableIsLocked(v *bool) *TeamUpdate {
	if v != nil {
		_u.SetIsLocked(*v)
	}
	return _u
}

// SetIsRegistered sets the "is_registered" field.
func (_u *TeamUpdate) SetIsRegistered(v bool) *TeamUpdate {
	_u.mutation.SetIsRegistered(v)
	return _u
}

// SetNillableIsRegistered sets the "is_registered" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableIsRegistered(v *bool) *TeamUpdate {
	if v != nil {
		_u.SetIsRegistered(*v)
	}
	return _u
}

// SetIsWaitlisted sets the "is_waitlisted" field.
func (_u *TeamUpdate) SetIsWaitlisted(v bool) *TeamUpdate {
	_u.mutation.SetIsWaitlisted(v)
	return _u
}

// SetNillableIsWaitlisted sets the "is_waitlisted" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableIsWaitlisted(v *bool) *TeamUpdate {
	if v != nil {
		_u.SetIsWaitlisted(*v)
	}
	return _u
}

// SetWaitlistPosition sets the "waitlist_position" field.
func (_u *TeamUpdate) SetWaitlistPosition(v int) *TeamUpdate {
	_u.mutation.ResetWaitlistPosition()
	_u.mutation.SetWaitlistPosition(v)
	return _u
}

// SetNillableWaitlistPosition sets the "waitlist_position" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableWaitlistPosition(v *int) *TeamUpdate {
	if v != nil {
		_u.SetWaitlistPosition(*v)
	}
	return _u
}

// AddWaitlistPosition adds value to the "waitlist_position" field.
func (_u *TeamUpdate) AddWaitlistPosition(v int) *TeamUpdate {
	_u.mutation.AddWaitlistPosition(v)
	return _u
}

// ClearWaitlistPosition clears the value of the "waitlist_position" field.
func (_u *TeamUpdate) ClearWaitlistPosition() *TeamUpdate {
	_u.mutation.ClearWaitlistPosition()
	return _u
}

// SetScore sets the "score" field.
func (_u *TeamUpdate) SetScore(v int) *TeamUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableScore(v *int) *TeamUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *TeamUpdate) AddScore(v int) *TeamUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// ClearScore clears the value of the "score" field.
func (_u *TeamUpdate) ClearScore() *TeamUpdate {
	_u.mutation.ClearScore()
	return _u
}

// SetElo sets the "elo" field.
func (_u *TeamUpdate) SetElo(v int) *TeamUpdate {
	_u.mutation.ResetElo()
	_u.mutation.SetElo(v)
	return _u
}

// SetNillableElo sets the "elo" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableElo(v *int) *TeamUpdate {
	if v != nil {
		_u.SetElo(*v)
	}
	return _u
}

// AddElo adds value to the "elo" field.
func (_u *TeamUpdate) AddElo(v int) *TeamUpdate {
	_u.mutation.AddElo(v)
	return _u
}

// ClearElo clears the value of the "elo" field.
func (_u *TeamUpdate) ClearElo() *TeamUpdate {
	_u.mutation.ClearElo()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TeamUpdate) SetCreatedAt(v time.Time) *TeamUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableCreatedAt(v *time.Time) *TeamUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamUpdate) SetUpdatedAt(v time.Time) *TeamUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTournamentID sets the "tournament" edge to the Tournament entity by ID.
func (_u *TeamUpdate) SetTournamentID(id int) *TeamUpdate {
	_u.mutation.SetTournamentID(id)
	return _u
}

// SetTournament sets the "tournament" edge to the Tournament entity.
func (_u *TeamUpdate) SetTournament(v *Tournament) *TeamUpdate {
	return _u.SetTournamentID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *TeamUpdate) SetCreatorID(id int) *TeamUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *TeamUpdate) SetCreator(v *User) *TeamUpdate {
	return _u.SetCreatorID(v.ID)
}

// AddMemberIDs adds the "members" edge to the TeamMember entity by IDs.
func (_u *TeamUpdate) AddMemberIDs(ids ...int) *TeamUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the TeamMember entity.
func (_u *TeamUpdate) AddMembers(v ...*TeamMember) *TeamUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// SetRankGroupID sets the "rank_group" edge to the RankGroup entity by ID.
func (_u *TeamUpdate) SetRankGroupID(id int) *TeamUpdate {
	_u.mutation.SetRankGroupID(id)
	return _u
}

// SetNillableRankGroupID sets the "rank_group" edge to the RankGroup entity by ID if the given value is not nil.
func (_u *TeamUpdate) SetNillableRankGroupID(id *int) *TeamUpdate {
	if id != nil {
		_u = _u.SetRankGroupID(*id)
	}
	return _u
}

// SetRankGroup sets the "rank_group" edge to the RankGroup entity.
func (_u *TeamUpdate) SetRankGroup(v *RankGroup) *TeamUpdate {
	return _u.SetRankGroupID(v.ID)
}

// AddInvitationIDs adds the "invitations" edge to the Invitation entity by IDs.
func (_u *TeamUpdate) AddInvitationIDs(ids ...int) *TeamUpdate {
	_u.mutation.AddInvitationIDs(ids...)
	return _u
}

// AddInvitations adds the "invitations" edges to the Invitation entity.
func (_u *TeamUpdate) AddInvitations(v ...*Invitation) *TeamUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvitationIDs(ids...)
}

// Mutation returns the TeamMutation object of the builder.
func (_u *TeamUpdate) Mutation() *TeamMutation {
	return _u.mutation
}

// ClearTournament clears the "tournament" edge to the Tournament entity.
func (_u *TeamUpdate) ClearTournament() *TeamUpdate {
	_u.mutation.ClearTournament()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *TeamUpdate) ClearCreator() *TeamUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearMembers clears all "members" edges to the TeamMember entity.
func (_u *TeamUpdate) ClearMembers() *TeamUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to TeamMember entities by IDs.
func (_u *TeamUpdate) RemoveMemberIDs(ids ...int) *TeamUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to TeamMember entities.
func (_u *TeamUpdate) RemoveMembers(v ...*TeamMember) *TeamUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearRankGroup clears the "rank_group" edge to the RankGroup entity.
func (_u *TeamUpdate) ClearRankGroup() *TeamUpdate {
	_u.mutation.ClearRankGroup()
	return _u
}

// ClearInvitations clears all "invitations" edges to the Invitation entity.
func (_u *TeamUpdate) ClearInvitations() *TeamUpdate {
	_u.mutation.ClearInvitations()
	return _u
}

// RemoveInvitationIDs removes the "invitations" edge to Invitation entities by IDs.
func (_u *TeamUpdate) RemoveInvitationIDs(ids ...int) *TeamUpdate {
	_u.mutation.RemoveInvitationIDs(ids...)
	return _u
}

// RemoveInvitations removes "invitations" edges to Invitation entities.
func (_u *TeamUpdate) RemoveInvitations(v ...*Invitation) *TeamUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvitationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := team.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamUpdate) check() error {
	if _u.mutation.TournamentCleared() && len(_u.mutation.TournamentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Team.tournament"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Team.creator"`)
	}
	return nil
}

func (_u *TeamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(team.Table, team.Columns, sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(team.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(team.FieldImageURL, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(team.FieldImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.IsLocked(); ok {
		_spec.SetField(team.FieldIsLocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsRegistered(); ok {
		_spec.SetField(team.FieldIsRegistered, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsWaitlisted(); ok {
		_spec.SetField(team.FieldIsWaitlisted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WaitlistPosition(); ok {
		_spec.SetField(team.FieldWaitlistPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWaitlistPosition(); ok {
		_spec.AddField(team.FieldWaitlistPosition, field.TypeInt, value)
	}
	if _u.mutation.WaitlistPositionCleared() {
		_spec.ClearField(team.FieldWaitlistPosition, field.TypeInt)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(team.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(team.FieldScore, field.TypeInt, value)
	}
	if _u.mutation.ScoreCleared() {
		_spec.ClearField(team.FieldScore, field.TypeInt)
	}
	if value, ok := _u.mutation.Elo(); ok {
		_spec.SetField(team.FieldElo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedElo(); ok {
		_spec.AddField(team.FieldElo, field.TypeInt, value)
	}
	if _u.mutation.EloCleared() {
		_spec.ClearField(team.FieldElo, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(team.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(team.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TournamentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.TournamentTable,
			Columns: []string{team.TournamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TournamentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.TournamentTable,
			Columns: []string{team.TournamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.CreatorTable,
			Columns: []string{team.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.CreatorTable,
			Columns: []string{team.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembersTable,
			Columns: []string{team.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembersTable,
			Columns: []string{team.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembersTable,
			Columns: []string{team.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RankGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.RankGroupTable,
			Columns: []string{team.RankGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankgroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RankGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.RankGroupTable,
			Columns: []string{team.RankGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.InvitationsTable,
			Columns: []string{team.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvitationsIDs(); len(nodes) > 0 && !_u.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.InvitationsTable,
			Columns: []string{team.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.InvitationsTable,
			Columns: []string{team.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{team.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamUpdateOne is the builder for updating a single Team entity.
type TeamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamMutation
}

// SetName sets the "name" field.
func (_u *TeamUpdateOne) SetName(v string) *TeamUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableName(v *string) *TeamUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *TeamUpdateOne) SetImageURL(v string) *TeamUpdateOne {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableImageURL(v *string) *TeamUpdateOne {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// ClearImageURL clears the value of the "image_url" field.
func (_u *TeamUpdateOne) ClearImageURL() *TeamUpdateOne {
	_u.mutation.ClearImageURL()
	return _u
}

// SetIsLocked sets the "is_locked" field.
func (_u *TeamUpdateOne) SetIsLocked(v bool) *TeamUpdateOne {
	_u.mutation.SetIsLocked(v)
	return _u
}

// SetNillableIsLocked sets the "is_locked" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableIsLocked(v *bool) *TeamUpdateOne {
	if v != nil {
		_u.SetIsLocked(*v)
	}
	return _u
}

// SetIsRegistered sets the "is_registered" field.
func (_u *TeamUpdateOne) SetIsRegistered(v bool) *TeamUpdateOne {
	_u.mutation.SetIsRegistered(v)
	return _u
}

// SetNillableIsRegistered sets the "is_registered" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableIsRegistered(v *bool) *TeamUpdateOne {
	if v != nil {
		_u.SetIsRegistered(*v)
	}
	return _u
}

// SetIsWaitlisted sets the "is_waitlisted" field.
func (_u *TeamUpdateOne) SetIsWaitlisted(v bool) *TeamUpdateOne {
	_u.mutation.SetIsWaitlisted(v)
	return _u
}

// SetNillableIsWaitlisted sets the "is_waitlisted" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableIsWaitlisted(v *bool) *TeamUpdateOne {
	if v != nil {
		_u.SetIsWaitlisted(*v)
	}
	return _u
}

// SetWaitlistPosition sets the "waitlist_position" field.
func (_u *TeamUpdateOne) SetWaitlistPosition(v int) *TeamUpdateOne {
	_u.mutation.ResetWaitlistPosition()
	_u.mutation.SetWaitlistPosition(v)
	return _u
}

// SetNillableWaitlistPosition sets the "waitlist_position" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableWaitlistPosition(v *int) *TeamUpdateOne {
	if v != nil {
		_u.SetWaitlistPosition(*v)
	}
	return _u
}

// AddWaitlistPosition adds value to the "waitlist_position" field.
func (_u *TeamUpdateOne) AddWaitlistPosition(v int) *TeamUpdateOne {
	_u.mutation.AddWaitlistPosition(v)
	return _u
}

// ClearWaitlistPosition clears the value of the "waitlist_position" field.
func (_u *TeamUpdateOne) ClearWaitlistPosition() *TeamUpdateOne {
	_u.mutation.ClearWaitlistPosition()
	return _u
}

// SetScore sets the "score" field.
func (_u *TeamUpdateOne) SetScore(v int) *TeamUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableScore(v *int) *TeamUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *TeamUpdateOne) AddScore(v int) *TeamUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// ClearScore clears the value of the "score" field.
func (_u *TeamUpdateOne) ClearScore() *TeamUpdateOne {
	_u.mutation.ClearScore()
	return _u
}

// SetElo sets the "elo" field.
func (_u *TeamUpdateOne) SetElo(v int) *TeamUpdateOne {
	_u.mutation.ResetElo()
	_u.mutation.SetElo(v)
	return _u
}

// SetNillableElo sets the "elo" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableElo(v *int) *TeamUpdateOne {
	if v != nil {
		_u.SetElo(*v)
	}
	return _u
}

// AddElo adds value to the "elo" field.
func (_u *TeamUpdateOne) AddElo(v int) *TeamUpdateOne {
	_u.mutation.AddElo(v)
	return _u
}

// ClearElo clears the value of the "elo" field.
func (_u *TeamUpdateOne) ClearElo() *TeamUpdateOne {
	_u.mutation.ClearElo()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TeamUpdateOne) SetCreatedAt(v time.Time) *TeamUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableCreatedAt(v *time.Time) *TeamUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamUpdateOne) SetUpdatedAt(v time.Time) *TeamUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTournamentID sets the "tournament" edge to the Tournament entity by ID.
func (_u *TeamUpdateOne) SetTournamentID(id int) *TeamUpdateOne {
	_u.mutation.SetTournamentID(id)
	return _u
}

// SetTournament sets the "tournament" edge to the Tournament entity.
func (_u *TeamUpdateOne) SetTournament(v *Tournament) *TeamUpdateOne {
	return _u.SetTournamentID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *TeamUpdateOne) SetCreatorID(id int) *TeamUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *TeamUpdateOne) SetCreator(v *User) *TeamUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// AddMemberIDs adds the "members" edge to the TeamMember entity by IDs.
func (_u *TeamUpdateOne) AddMemberIDs(ids ...int) *TeamUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the TeamMember entity.
func (_u *TeamUpdateOne) AddMembers(v ...*TeamMember) *TeamUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// SetRankGroupID sets the "rank_group" edge to the RankGroup entity by ID.
func (_u *TeamUpdateOne) SetRankGroupID(id int) *TeamUpdateOne {
	_u.mutation.SetRankGroupID(id)
	return _u
}

// SetNillableRankGroupID sets the "rank_group" edge to the RankGroup entity by ID if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableRankGroupID(id *int) *TeamUpdateOne {
	if id != nil {
		_u = _u.SetRankGroupID(*id)
	}
	return _u
}

// SetRankGroup sets the "rank_group" edge to the RankGroup entity.
func (_u *TeamUpdateOne) SetRankGroup(v *RankGroup) *TeamUpdateOne {
	return _u.SetRankGroupID(v.ID)
}

// AddInvitationIDs adds the "invitations" edge to the Invitation entity by IDs.
func (_u *TeamUpdateOne) AddInvitationIDs(ids ...int) *TeamUpdateOne {
	_u.mutation.AddInvitationIDs(ids...)
	return _u
}

// AddInvitations adds the "invitations" edges to the Invitation entity.
func (_u *TeamUpdateOne) AddInvitations(v ...*Invitation) *TeamUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvitationIDs(ids...)
}

// Mutation returns the TeamMutation object of the builder.
func (_u *TeamUpdateOne) Mutation() *TeamMutation {
	return _u.mutation
}

// ClearTournament clears the "tournament" edge to the Tournament entity.
func (_u *TeamUpdateOne) ClearTournament() *TeamUpdateOne {
	_u.mutation.ClearTournament()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *TeamUpdateOne) ClearCreator() *TeamUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearMembers clears all "members" edges to the TeamMember entity.
func (_u *TeamUpdateOne) ClearMembers() *TeamUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to TeamMember entities by IDs.
func (_u *TeamUpdateOne) RemoveMemberIDs(ids ...int) *TeamUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to TeamMember entities.
func (_u *TeamUpdateOne) RemoveMembers(v ...*TeamMember) *TeamUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearRankGroup clears the "rank_group" edge to the RankGroup entity.
func (_u *TeamUpdateOne) ClearRankGroup() *TeamUpdateOne {
	_u.mutation.ClearRankGroup()
	return _u
}

// ClearInvitations clears all "invitations" edges to the Invitation entity.
func (_u *TeamUpdateOne) ClearInvitations() *TeamUpdateOne {
	_u.mutation.ClearInvitations()
	return _u
}

// RemoveInvitationIDs removes the "invitations" edge to Invitation entities by IDs.
func (_u *TeamUpdateOne) RemoveInvitationIDs(ids ...int) *TeamUpdateOne {
	_u.mutation.RemoveInvitationIDs(ids...)
	return _u
}

// RemoveInvitations removes "invitations" edges to Invitation entities.
func (_u *TeamUpdateOne) RemoveInvitations(v ...*Invitation) *TeamUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvitationIDs(ids...)
}

// Where appends a list predicates to the TeamUpdate builder.
func (_u *TeamUpdateOne) Where(ps ...predicate.Team) *TeamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamUpdateOne) Select(field string, fields ...string) *TeamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Team entity.
func (_u *TeamUpdateOne) Save(ctx context.Context) (*Team, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUpdateOne) SaveX(ctx context.Context) *Team {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := team.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamUpdateOne) check() error {
	if _u.mutation.TournamentCleared() && len(_u.mutation.TournamentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Team.tournament"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Team.creator"`)
	}
	return nil
}

func (_u *TeamUpdateOne) sqlSave(ctx context.Context) (_node *Team, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(team.Table, team.Columns, sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Team.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, team.FieldID)
		for _, f := range fields {
			if !team.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != team.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(team.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(team.FieldImageURL, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(team.FieldImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.IsLocked(); ok {
		_spec.SetField(team.FieldIsLocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsRegistered(); ok {
		_spec.SetField(team.FieldIsRegistered, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsWaitlisted(); ok {
		_spec.SetField(team.FieldIsWaitlisted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WaitlistPosition(); ok {
		_spec.SetField(team.FieldWaitlistPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWaitlistPosition(); ok {
		_spec.AddField(team.FieldWaitlistPosition, field.TypeInt, value)
	}
	if _u.mutation.WaitlistPositionCleared() {
		_spec.ClearField(team.FieldWaitlistPosition, field.TypeInt)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(team.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(team.FieldScore, field.TypeInt, value)
	}
	if _u.mutation.ScoreCleared() {
		_spec.ClearField(team.FieldScore, field.TypeInt)
	}
	if value, ok := _u.mutation.Elo(); ok {
		_spec.SetField(team.FieldElo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedElo(); ok {
		_spec.AddField(team.FieldElo, field.TypeInt, value)
	}
	if _u.mutation.EloCleared() {
		_spec.ClearField(team.FieldElo, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(team.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(team.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TournamentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.TournamentTable,
			Columns: []string{team.TournamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TournamentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.TournamentTable,
			Columns: []string{team.TournamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.CreatorTable,
			Columns: []string{team.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.CreatorTable,
			Columns: []string{team.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembersTable,
			Columns: []string{team.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembersTable,
			Columns: []string{team.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembersTable,
			Columns: []string{team.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RankGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.RankGroupTable,
			Columns: []string{team.RankGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankgroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RankGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.RankGroupTable,
			Columns: []string{team.RankGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.InvitationsTable,
			Columns: []string{team.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvitationsIDs(); len(nodes) > 0 && !_u.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.InvitationsTable,
			Columns: []string{team.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.InvitationsTable,
			Columns: []string{team.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Team{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{team.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
