// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-website/ent/predicate"
	"base-website/ent/rankgroup"
	"base-website/ent/team"
	"base-website/ent/teammember"
	"base-website/ent/tournament"
	"base-website/ent/tournamentadmin"
	"base-website/ent/user"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TournamentQuery is the builder for querying Tournament entities.
type TournamentQuery struct {
	config
	ctx             *QueryContext
	order           []tournament.OrderOption
	inters          []Interceptor
	predicates      []predicate.Tournament
	withCreator     *UserQuery
	withAdmins      *TournamentAdminQuery
	withTeams       *TeamQuery
	withRankGroups  *RankGroupQuery
	withTeamMembers *TeamMemberQuery
	withFKs         bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TournamentQuery builder.
func (_q *TournamentQuery) Where(ps ...predicate.Tournament) *TournamentQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TournamentQuery) Limit(limit int) *TournamentQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TournamentQuery) Offset(offset int) *TournamentQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TournamentQuery) Unique(unique bool) *TournamentQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TournamentQuery) Order(o ...tournament.OrderOption) *TournamentQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCreator chains the current query on the "creator" edge.
func (_q *TournamentQuery) QueryCreator() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tournament.Table, tournament.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tournament.CreatorTable, tournament.CreatorColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAdmins chains the current query on the "admins" edge.
func (_q *TournamentQuery) QueryAdmins() *TournamentAdminQuery {
	query := (&TournamentAdminClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tournament.Table, tournament.FieldID, selector),
			sqlgraph.To(tournamentadmin.Table, tournamentadmin.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tournament.AdminsTable, tournament.AdminsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTeams chains the current query on the "teams" edge.
func (_q *TournamentQuery) QueryTeams() *TeamQuery {
	query := (&TeamClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tournament.Table, tournament.FieldID, selector),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tournament.TeamsTable, tournament.TeamsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRankGroups chains the current query on the "rank_groups" edge.
func (_q *TournamentQuery) QueryRankGroups() *RankGroupQuery {
	query := (&RankGroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tournament.Table, tournament.FieldID, selector),
			sqlgraph.To(rankgroup.Table, rankgroup.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tournament.RankGroupsTable, tournament.RankGroupsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTeamMembers chains the current query on the "team_members" edge.
func (_q *TournamentQuery) QueryTeamMembers() *TeamMemberQuery {
	query := (&TeamMemberClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tournament.Table, tournament.FieldID, selector),
			sqlgraph.To(teammember.Table, teammember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tournament.TeamMembersTable, tournament.TeamMembersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Tournament entity from the query.
// Returns a *NotFoundError when no Tournament was found.
func (_q *TournamentQuery) First(ctx context.Context) (*Tournament, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tournament.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TournamentQuery) FirstX(ctx context.Context) *Tournament {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Tournament ID from the query.
// Returns a *NotFoundError when no Tournament ID was found.
func (_q *TournamentQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tournament.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TournamentQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Tournament entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Tournament entity is found.
// Returns a *NotFoundError when no Tournament entities are found.
func (_q *TournamentQuery) Only(ctx context.Context) (*Tournament, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tournament.Label}
	default:
		return nil, &NotSingularError{tournament.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TournamentQuery) OnlyX(ctx context.Context) *Tournament {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Tournament ID in the query.
// Returns a *NotSingularError when more than one Tournament ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TournamentQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tournament.Label}
	default:
		err = &NotSingularError{tournament.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TournamentQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Tournaments.
func (_q *TournamentQuery) All(ctx context.Context) ([]*Tournament, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Tournament, *TournamentQuery]()
	return withInterceptors[[]*Tournament](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TournamentQuery) AllX(ctx context.Context) []*Tournament {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Tournament IDs.
func (_q *TournamentQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(tournament.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TournamentQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TournamentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TournamentQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TournamentQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TournamentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TournamentQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TournamentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TournamentQuery) Clone() *TournamentQuery {
	if _q == nil {
		return nil
	}
	return &TournamentQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]tournament.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.Tournament{}, _q.predicates...),
		withCreator:     _q.withCreator.Clone(),
		withAdmins:      _q.withAdmins.Clone(),
		withTeams:       _q.withTeams.Clone(),
		withRankGroups:  _q.withRankGroups.Clone(),
		withTeamMembers: _q.withTeamMembers.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCreator tells the query-builder to eager-load the nodes that are connected to
// the "creator" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TournamentQuery) WithCreator(opts ...func(*UserQuery)) *TournamentQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCreator = query
	return _q
}

// WithAdmins tells the query-builder to eager-load the nodes that are connected to
// the "admins" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TournamentQuery) WithAdmins(opts ...func(*TournamentAdminQuery)) *TournamentQuery {
	query := (&TournamentAdminClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAdmins = query
	return _q
}

// WithTeams tells the query-builder to eager-load the nodes that are connected to
// the "teams" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TournamentQuery) WithTeams(opts ...func(*TeamQuery)) *TournamentQuery {
	query := (&TeamClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTeams = query
	return _q
}

// WithRankGroups tells the query-builder to eager-load the nodes that are connected to
// the "rank_groups" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TournamentQuery) WithRankGroups(opts ...func(*RankGroupQuery)) *TournamentQuery {
	query := (&RankGroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRankGroups = query
	return _q
}

// WithTeamMembers tells the query-builder to eager-load the nodes that are connected to
// the "team_members" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TournamentQuery) WithTeamMembers(opts ...func(*TeamMemberQuery)) *TournamentQuery {
	query := (&TeamMemberClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTeamMembers = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Slug string `json:"slug,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Tournament.Query().
//		GroupBy(tournament.FieldSlug).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *TournamentQuery) GroupBy(field string, fields ...string) *TournamentGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TournamentGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = tournament.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Slug string `json:"slug,omitempty"`
//	}
//
//	client.Tournament.Query().
//		Select(tournament.FieldSlug).
//		Scan(ctx, &v)
func (_q *TournamentQuery) Select(fields ...string) *TournamentSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TournamentSelect{TournamentQuery: _q}
	sbuild.label = tournament.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TournamentSelect configured with the given aggregations.
func (_q *TournamentQuery) Aggregate(fns ...AggregateFunc) *TournamentSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TournamentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !tournament.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *TournamentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Tournament, error) {
	var (
		nodes       = []*Tournament{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withCreator != nil,
			_q.withAdmins != nil,
			_q.withTeams != nil,
			_q.withRankGroups != nil,
			_q.withTeamMembers != nil,
		}
	)
	if _q.withCreator != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, tournament.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Tournament).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Tournament{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCreator; query != nil {
		if err := _q.loadCreator(ctx, query, nodes, nil,
			func(n *Tournament, e *User) { n.Edges.Creator = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAdmins; query != nil {
		if err := _q.loadAdmins(ctx, query, nodes,
			func(n *Tournament) { n.Edges.Admins = []*TournamentAdmin{} },
			func(n *Tournament, e *TournamentAdmin) { n.Edges.Admins = append(n.Edges.Admins, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTeams; query != nil {
		if err := _q.loadTeams(ctx, query, nodes,
			func(n *Tournament) { n.Edges.Teams = []*Team{} },
			func(n *Tournament, e *Team) { n.Edges.Teams = append(n.Edges.Teams, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRankGroups; query != nil {
		if err := _q.loadRankGroups(ctx, query, nodes,
			func(n *Tournament) { n.Edges.RankGroups = []*RankGroup{} },
			func(n *Tournament, e *RankGroup) { n.Edges.RankGroups = append(n.Edges.RankGroups, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTeamMembers; query != nil {
		if err := _q.loadTeamMembers(ctx, query, nodes,
			func(n *Tournament) { n.Edges.TeamMembers = []*TeamMember{} },
			func(n *Tournament, e *TeamMember) { n.Edges.TeamMembers = append(n.Edges.TeamMembers, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TournamentQuery) loadCreator(ctx context.Context, query *UserQuery, nodes []*Tournament, init func(*Tournament), assign func(*Tournament, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Tournament)
	for i := range nodes {
		if nodes[i].user_created_tournaments == nil {
			continue
		}
		fk := *nodes[i].user_created_tournaments
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_created_tournaments" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *TournamentQuery) loadAdmins(ctx context.Context, query *TournamentAdminQuery, nodes []*Tournament, init func(*Tournament), assign func(*Tournament, *TournamentAdmin)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tournament)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.TournamentAdmin(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tournament.AdminsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.tournament_admins
		if fk == nil {
			return fmt.Errorf(`foreign-key "tournament_admins" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tournament_admins" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TournamentQuery) loadTeams(ctx context.Context, query *TeamQuery, nodes []*Tournament, init func(*Tournament), assign func(*Tournament, *Team)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tournament)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Team(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tournament.TeamsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.tournament_teams
		if fk == nil {
			return fmt.Errorf(`foreign-key "tournament_teams" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tournament_teams" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TournamentQuery) loadRankGroups(ctx context.Context, query *RankGroupQuery, nodes []*Tournament, init func(*Tournament), assign func(*Tournament, *RankGroup)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tournament)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.RankGroup(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tournament.RankGroupsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.tournament_rank_groups
		if fk == nil {
			return fmt.Errorf(`foreign-key "tournament_rank_groups" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tournament_rank_groups" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TournamentQuery) loadTeamMembers(ctx context.Context, query *TeamMemberQuery, nodes []*Tournament, init func(*Tournament), assign func(*Tournament, *TeamMember)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tournament)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.TeamMember(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tournament.TeamMembersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.tournament_team_members
		if fk == nil {
			return fmt.Errorf(`foreign-key "tournament_team_members" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tournament_team_members" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *TournamentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TournamentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tournament.Table, tournament.Columns, sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tournament.FieldID)
		for i := range fields {
			if fields[i] != tournament.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TournamentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(tournament.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = tournament.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TournamentGroupBy is the group-by builder for Tournament entities.
type TournamentGroupBy struct {
	selector
	build *TournamentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TournamentGroupBy) Aggregate(fns ...AggregateFunc) *TournamentGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TournamentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TournamentQuery, *TournamentGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TournamentGroupBy) sqlScan(ctx context.Context, root *TournamentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TournamentSelect is the builder for selecting fields of Tournament entities.
type TournamentSelect struct {
	*TournamentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TournamentSelect) Aggregate(fns ...AggregateFunc) *TournamentSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TournamentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TournamentQuery, *TournamentSelect](ctx, _s.TournamentQuery, _s, _s.inters, v)
}

func (_s *TournamentSelect) sqlScan(ctx context.Context, root *TournamentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
