// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-website/ent/tournament"
	"base-website/ent/tournamentadmin"
	"base-website/ent/user"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TournamentAdmin is the model entity for the TournamentAdmin schema.
type TournamentAdmin struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Role holds the value of the "role" field.
	Role tournamentadmin.Role `json:"role,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TournamentAdminQuery when eager-loading is set.
	Edges                       TournamentAdminEdges `json:"edges"`
	tournament_admins           *int
	user_tournament_admin_roles *int
	selectValues                sql.SelectValues
}

// TournamentAdminEdges holds the relations/edges for other nodes in the graph.
type TournamentAdminEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Tournament holds the value of the tournament edge.
	Tournament *Tournament `json:"tournament,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TournamentAdminEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// TournamentOrErr returns the Tournament value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TournamentAdminEdges) TournamentOrErr() (*Tournament, error) {
	if e.Tournament != nil {
		return e.Tournament, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: tournament.Label}
	}
	return nil, &NotLoadedError{edge: "tournament"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TournamentAdmin) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tournamentadmin.FieldID:
			values[i] = new(sql.NullInt64)
		case tournamentadmin.FieldRole:
			values[i] = new(sql.NullString)
		case tournamentadmin.ForeignKeys[0]: // tournament_admins
			values[i] = new(sql.NullInt64)
		case tournamentadmin.ForeignKeys[1]: // user_tournament_admin_roles
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TournamentAdmin fields.
func (_m *TournamentAdmin) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tournamentadmin.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case tournamentadmin.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = tournamentadmin.Role(value.String)
			}
		case tournamentadmin.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field tournament_admins", value)
			} else if value.Valid {
				_m.tournament_admins = new(int)
				*_m.tournament_admins = int(value.Int64)
			}
		case tournamentadmin.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_tournament_admin_roles", value)
			} else if value.Valid {
				_m.user_tournament_admin_roles = new(int)
				*_m.user_tournament_admin_roles = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TournamentAdmin.
// This includes values selected through modifiers, order, etc.
func (_m *TournamentAdmin) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the TournamentAdmin entity.
func (_m *TournamentAdmin) QueryUser() *UserQuery {
	return NewTournamentAdminClient(_m.config).QueryUser(_m)
}

// QueryTournament queries the "tournament" edge of the TournamentAdmin entity.
func (_m *TournamentAdmin) QueryTournament() *TournamentQuery {
	return NewTournamentAdminClient(_m.config).QueryTournament(_m)
}

// Update returns a builder for updating this TournamentAdmin.
// Note that you need to call TournamentAdmin.Unwrap() before calling this method if this TournamentAdmin
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TournamentAdmin) Update() *TournamentAdminUpdateOne {
	return NewTournamentAdminClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TournamentAdmin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TournamentAdmin) Unwrap() *TournamentAdmin {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TournamentAdmin is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TournamentAdmin) String() string {
	var builder strings.Builder
	builder.WriteString("TournamentAdmin(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", _m.Role))
	builder.WriteByte(')')
	return builder.String()
}

// TournamentAdmins is a parsable slice of TournamentAdmin.
type TournamentAdmins []*TournamentAdmin
