// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-website/ent/predicate"
	"base-website/ent/rankgroup"
	"base-website/ent/team"
	"base-website/ent/tournament"
	"base-website/ent/tournamentadmin"
	"base-website/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TournamentUpdate is the builder for updating Tournament entities.
type TournamentUpdate struct {
	config
	hooks    []Hook
	mutation *TournamentMutation
}

// Where appends a list predicates to the TournamentUpdate builder.
func (_u *TournamentUpdate) Where(ps ...predicate.Tournament) *TournamentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *TournamentUpdate) SetSlug(v string) *TournamentUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *TournamentUpdate) SetNillableSlug(v *string) *TournamentUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TournamentUpdate) SetName(v string) *TournamentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TournamentUpdate) SetNillableName(v *string) *TournamentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TournamentUpdate) SetDescription(v string) *TournamentUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TournamentUpdate) SetNillableDescription(v *string) *TournamentUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIsVisible sets the "is_visible" field.
func (_u *TournamentUpdate) SetIsVisible(v bool) *TournamentUpdate {
	_u.mutation.SetIsVisible(v)
	return _u
}

// SetNillableIsVisible sets the "is_visible" field if the given value is not nil.
func (_u *TournamentUpdate) SetNillableIsVisible(v *bool) *TournamentUpdate {
	if v != nil {
		_u.SetIsVisible(*v)
	}
	return _u
}

// SetRegistrationStart sets the "registration_start" field.
func (_u *TournamentUpdate) SetRegistrationStart(v time.Time) *TournamentUpdate {
	_u.mutation.SetRegistrationStart(v)
	return _u
}

// SetNillableRegistrationStart sets the "registration_start" field if the given value is not nil.
func (_u *TournamentUpdate) SetNillableRegistrationStart(v *time.Time) *TournamentUpdate {
	if v != nil {
		_u.SetRegistrationStart(*v)
	}
	return _u
}

// SetRegistrationEnd sets the "registration_end" field.
func (_u *TournamentUpdate) SetRegistrationEnd(v time.Time) *TournamentUpdate {
	_u.mutation.SetRegistrationEnd(v)
	return _u
}

// SetNillableRegistrationEnd sets the "registration_end" field if the given value is not nil.
func (_u *TournamentUpdate) SetNillableRegistrationEnd(v *time.Time) *TournamentUpdate {
	if v != nil {
		_u.SetRegistrationEnd(*v)
	}
	return _u
}

// SetTournamentStart sets the "tournament_start" field.
func (_u *TournamentUpdate) SetTournamentStart(v time.Time) *TournamentUpdate {
	_u.mutation.SetTournamentStart(v)
	return _u
}

// SetNillableTournamentStart sets the "tournament_start" field if the given value is not nil.
func (_u *TournamentUpdate) SetNillableTournamentStart(v *time.Time) *TournamentUpdate {
	if v != nil {
		_u.SetTournamentStart(*v)
	}
	return _u
}

// SetTournamentEnd sets the "tournament_end" field.
func (_u *TournamentUpdate) SetTournamentEnd(v time.Time) *TournamentUpdate {
	_u.mutation.SetTournamentEnd(v)
	return _u
}

// SetNillableTournamentEnd sets the "tournament_end" field if the given value is not nil.
func (_u *TournamentUpdate) SetNillableTournamentEnd(v *time.Time) *TournamentUpdate {
	if v != nil {
		_u.SetTournamentEnd(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *TournamentUpdate) SetState(v tournament.State) *TournamentUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *TournamentUpdate) SetNillableState(v *tournament.State) *TournamentUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetMaxTeams sets the "max_teams" field.
func (_u *TournamentUpdate) SetMaxTeams(v int) *TournamentUpdate {
	_u.mutation.ResetMaxTeams()
	_u.mutation.SetMaxTeams(v)
	return _u
}

// SetNillableMaxTeams sets the "max_teams" field if the given value is not nil.
func (_u *TournamentUpdate) SetNillableMaxTeams(v *int) *TournamentUpdate {
	if v != nil {
		_u.SetMaxTeams(*v)
	}
	return _u
}

// AddMaxTeams adds value to the "max_teams" field.
func (_u *TournamentUpdate) AddMaxTeams(v int) *TournamentUpdate {
	_u.mutation.AddMaxTeams(v)
	return _u
}

// SetTeamStructure sets the "team_structure" field.
func (_u *TournamentUpdate) SetTeamStructure(v map[string]interface{}) *TournamentUpdate {
	_u.mutation.SetTeamStructure(v)
	return _u
}

// ClearTeamStructure clears the value of the "team_structure" field.
func (_u *TournamentUpdate) ClearTeamStructure() *TournamentUpdate {
	_u.mutation.ClearTeamStructure()
	return _u
}

// SetCustomPageComponent sets the "custom_page_component" field.
func (_u *TournamentUpdate) SetCustomPageComponent(v string) *TournamentUpdate {
	_u.mutation.SetCustomPageComponent(v)
	return _u
}

// SetNillableCustomPageComponent sets the "custom_page_component" field if the given value is not nil.
func (_u *TournamentUpdate) SetNillableCustomPageComponent(v *string) *TournamentUpdate {
	if v != nil {
		_u.SetCustomPageComponent(*v)
	}
	return _u
}

// SetExternalLink sets the "external_link" field.
func (_u *TournamentUpdate) SetExternalLink(v string) *TournamentUpdate {
	_u.mutation.SetExternalLink(v)
	return _u
}

// SetNillableExternalLink sets the "external_link" field if the given value is not nil.
func (_u *TournamentUpdate) SetNillableExternalLink(v *string) *TournamentUpdate {
	if v != nil {
		_u.SetExternalLink(*v)
	}
	return _u
}

// ClearExternalLink clears the value of the "external_link" field.
func (_u *TournamentUpdate) ClearExternalLink() *TournamentUpdate {
	_u.mutation.ClearExternalLink()
	return _u
}

// SetResults sets the "results" field.
func (_u *TournamentUpdate) SetResults(v map[string]interface{}) *TournamentUpdate {
	_u.mutation.SetResults(v)
	return _u
}

// ClearResults clears the value of the "results" field.
func (_u *TournamentUpdate) ClearResults() *TournamentUpdate {
	_u.mutation.ClearResults()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TournamentUpdate) SetCreatedAt(v time.Time) *TournamentUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TournamentUpdate) SetNillableCreatedAt(v *time.Time) *TournamentUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *TournamentUpdate) SetCreatorID(id int) *TournamentUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *TournamentUpdate) SetCreator(v *User) *TournamentUpdate {
	return _u.SetCreatorID(v.ID)
}

// AddAdminIDs adds the "admins" edge to the TournamentAdmin entity by IDs.
func (_u *TournamentUpdate) AddAdminIDs(ids ...int) *TournamentUpdate {
	_u.mutation.AddAdminIDs(ids...)
	return _u
}

// AddAdmins adds the "admins" edges to the TournamentAdmin entity.
func (_u *TournamentUpdate) AddAdmins(v ...*TournamentAdmin) *TournamentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdminIDs(ids...)
}

// AddTeamIDs adds the "teams" edge to the Team entity by IDs.
func (_u *TournamentUpdate) AddTeamIDs(ids ...int) *TournamentUpdate {
	_u.mutation.AddTeamIDs(ids...)
	return _u
}

// AddTeams adds the "teams" edges to the Team entity.
func (_u *TournamentUpdate) AddTeams(v ...*Team) *TournamentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamIDs(ids...)
}

// AddRankGroupIDs adds the "rank_groups" edge to the RankGroup entity by IDs.
func (_u *TournamentUpdate) AddRankGroupIDs(ids ...int) *TournamentUpdate {
	_u.mutation.AddRankGroupIDs(ids...)
	return _u
}

// AddRankGroups adds the "rank_groups" edges to the RankGroup entity.
func (_u *TournamentUpdate) AddRankGroups(v ...*RankGroup) *TournamentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRankGroupIDs(ids...)
}

// Mutation returns the TournamentMutation object of the builder.
func (_u *TournamentUpdate) Mutation() *TournamentMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *TournamentUpdate) ClearCreator() *TournamentUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearAdmins clears all "admins" edges to the TournamentAdmin entity.
func (_u *TournamentUpdate) ClearAdmins() *TournamentUpdate {
	_u.mutation.ClearAdmins()
	return _u
}

// RemoveAdminIDs removes the "admins" edge to TournamentAdmin entities by IDs.
func (_u *TournamentUpdate) RemoveAdminIDs(ids ...int) *TournamentUpdate {
	_u.mutation.RemoveAdminIDs(ids...)
	return _u
}

// RemoveAdmins removes "admins" edges to TournamentAdmin entities.
func (_u *TournamentUpdate) RemoveAdmins(v ...*TournamentAdmin) *TournamentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdminIDs(ids...)
}

// ClearTeams clears all "teams" edges to the Team entity.
func (_u *TournamentUpdate) ClearTeams() *TournamentUpdate {
	_u.mutation.ClearTeams()
	return _u
}

// RemoveTeamIDs removes the "teams" edge to Team entities by IDs.
func (_u *TournamentUpdate) RemoveTeamIDs(ids ...int) *TournamentUpdate {
	_u.mutation.RemoveTeamIDs(ids...)
	return _u
}

// RemoveTeams removes "teams" edges to Team entities.
func (_u *TournamentUpdate) RemoveTeams(v ...*Team) *TournamentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamIDs(ids...)
}

// ClearRankGroups clears all "rank_groups" edges to the RankGroup entity.
func (_u *TournamentUpdate) ClearRankGroups() *TournamentUpdate {
	_u.mutation.ClearRankGroups()
	return _u
}

// RemoveRankGroupIDs removes the "rank_groups" edge to RankGroup entities by IDs.
func (_u *TournamentUpdate) RemoveRankGroupIDs(ids ...int) *TournamentUpdate {
	_u.mutation.RemoveRankGroupIDs(ids...)
	return _u
}

// RemoveRankGroups removes "rank_groups" edges to RankGroup entities.
func (_u *TournamentUpdate) RemoveRankGroups(v ...*RankGroup) *TournamentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRankGroupIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TournamentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TournamentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TournamentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TournamentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TournamentUpdate) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := tournament.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Tournament.state": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Tournament.creator"`)
	}
	return nil
}

func (_u *TournamentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tournament.Table, tournament.Columns, sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(tournament.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tournament.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tournament.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsVisible(); ok {
		_spec.SetField(tournament.FieldIsVisible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RegistrationStart(); ok {
		_spec.SetField(tournament.FieldRegistrationStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RegistrationEnd(); ok {
		_spec.SetField(tournament.FieldRegistrationEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TournamentStart(); ok {
		_spec.SetField(tournament.FieldTournamentStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TournamentEnd(); ok {
		_spec.SetField(tournament.FieldTournamentEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(tournament.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MaxTeams(); ok {
		_spec.SetField(tournament.FieldMaxTeams, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTeams(); ok {
		_spec.AddField(tournament.FieldMaxTeams, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TeamStructure(); ok {
		_spec.SetField(tournament.FieldTeamStructure, field.TypeJSON, value)
	}
	if _u.mutation.TeamStructureCleared() {
		_spec.ClearField(tournament.FieldTeamStructure, field.TypeJSON)
	}
	if value, ok := _u.mutation.CustomPageComponent(); ok {
		_spec.SetField(tournament.FieldCustomPageComponent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalLink(); ok {
		_spec.SetField(tournament.FieldExternalLink, field.TypeString, value)
	}
	if _u.mutation.ExternalLinkCleared() {
		_spec.ClearField(tournament.FieldExternalLink, field.TypeString)
	}
	if value, ok := _u.mutation.Results(); ok {
		_spec.SetField(tournament.FieldResults, field.TypeJSON, value)
	}
	if _u.mutation.ResultsCleared() {
		_spec.ClearField(tournament.FieldResults, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(tournament.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tournament.CreatorTable,
			Columns: []string{tournament.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tournament.CreatorTable,
			Columns: []string{tournament.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.AdminsTable,
			Columns: []string{tournament.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournamentadmin.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdminsIDs(); len(nodes) > 0 && !_u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.AdminsTable,
			Columns: []string{tournament.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournamentadmin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.AdminsTable,
			Columns: []string{tournament.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournamentadmin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.TeamsTable,
			Columns: []string{tournament.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamsIDs(); len(nodes) > 0 && !_u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.TeamsTable,
			Columns: []string{tournament.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.TeamsTable,
			Columns: []string{tournament.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RankGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.RankGroupsTable,
			Columns: []string{tournament.RankGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankgroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRankGroupsIDs(); len(nodes) > 0 && !_u.mutation.RankGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.RankGroupsTable,
			Columns: []string{tournament.RankGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RankGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.RankGroupsTable,
			Columns: []string{tournament.RankGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tournament.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TournamentUpdateOne is the builder for updating a single Tournament entity.
type TournamentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TournamentMutation
}

// SetSlug sets the "slug" field.
func (_u *TournamentUpdateOne) SetSlug(v string) *TournamentUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *TournamentUpdateOne) SetNillableSlug(v *string) *TournamentUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TournamentUpdateOne) SetName(v string) *TournamentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TournamentUpdateOne) SetNillableName(v *string) *TournamentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TournamentUpdateOne) SetDescription(v string) *TournamentUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TournamentUpdateOne) SetNillableDescription(v *string) *TournamentUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIsVisible sets the "is_visible" field.
func (_u *TournamentUpdateOne) SetIsVisible(v bool) *TournamentUpdateOne {
	_u.mutation.SetIsVisible(v)
	return _u
}

// SetNillableIsVisible sets the "is_visible" field if the given value is not nil.
func (_u *TournamentUpdateOne) SetNillableIsVisible(v *bool) *TournamentUpdateOne {
	if v != nil {
		_u.SetIsVisible(*v)
	}
	return _u
}

// SetRegistrationStart sets the "registration_start" field.
func (_u *TournamentUpdateOne) SetRegistrationStart(v time.Time) *TournamentUpdateOne {
	_u.mutation.SetRegistrationStart(v)
	return _u
}

// SetNillableRegistrationStart sets the "registration_start" field if the given value is not nil.
func (_u *TournamentUpdateOne) SetNillableRegistrationStart(v *time.Time) *TournamentUpdateOne {
	if v != nil {
		_u.SetRegistrationStart(*v)
	}
	return _u
}

// SetRegistrationEnd sets the "registration_end" field.
func (_u *TournamentUpdateOne) SetRegistrationEnd(v time.Time) *TournamentUpdateOne {
	_u.mutation.SetRegistrationEnd(v)
	return _u
}

// SetNillableRegistrationEnd sets the "registration_end" field if the given value is not nil.
func (_u *TournamentUpdateOne) SetNillableRegistrationEnd(v *time.Time) *TournamentUpdateOne {
	if v != nil {
		_u.SetRegistrationEnd(*v)
	}
	return _u
}

// SetTournamentStart sets the "tournament_start" field.
func (_u *TournamentUpdateOne) SetTournamentStart(v time.Time) *TournamentUpdateOne {
	_u.mutation.SetTournamentStart(v)
	return _u
}

// SetNillableTournamentStart sets the "tournament_start" field if the given value is not nil.
func (_u *TournamentUpdateOne) SetNillableTournamentStart(v *time.Time) *TournamentUpdateOne {
	if v != nil {
		_u.SetTournamentStart(*v)
	}
	return _u
}

// SetTournamentEnd sets the "tournament_end" field.
func (_u *TournamentUpdateOne) SetTournamentEnd(v time.Time) *TournamentUpdateOne {
	_u.mutation.SetTournamentEnd(v)
	return _u
}

// SetNillableTournamentEnd sets the "tournament_end" field if the given value is not nil.
func (_u *TournamentUpdateOne) SetNillableTournamentEnd(v *time.Time) *TournamentUpdateOne {
	if v != nil {
		_u.SetTournamentEnd(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *TournamentUpdateOne) SetState(v tournament.State) *TournamentUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *TournamentUpdateOne) SetNillableState(v *tournament.State) *TournamentUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetMaxTeams sets the "max_teams" field.
func (_u *TournamentUpdateOne) SetMaxTeams(v int) *TournamentUpdateOne {
	_u.mutation.ResetMaxTeams()
	_u.mutation.SetMaxTeams(v)
	return _u
}

// SetNillableMaxTeams sets the "max_teams" field if the given value is not nil.
func (_u *TournamentUpdateOne) SetNillableMaxTeams(v *int) *TournamentUpdateOne {
	if v != nil {
		_u.SetMaxTeams(*v)
	}
	return _u
}

// AddMaxTeams adds value to the "max_teams" field.
func (_u *TournamentUpdateOne) AddMaxTeams(v int) *TournamentUpdateOne {
	_u.mutation.AddMaxTeams(v)
	return _u
}

// SetTeamStructure sets the "team_structure" field.
func (_u *TournamentUpdateOne) SetTeamStructure(v map[string]interface{}) *TournamentUpdateOne {
	_u.mutation.SetTeamStructure(v)
	return _u
}

// ClearTeamStructure clears the value of the "team_structure" field.
func (_u *TournamentUpdateOne) ClearTeamStructure() *TournamentUpdateOne {
	_u.mutation.ClearTeamStructure()
	return _u
}

// SetCustomPageComponent sets the "custom_page_component" field.
func (_u *TournamentUpdateOne) SetCustomPageComponent(v string) *TournamentUpdateOne {
	_u.mutation.SetCustomPageComponent(v)
	return _u
}

// SetNillableCustomPageComponent sets the "custom_page_component" field if the given value is not nil.
func (_u *TournamentUpdateOne) SetNillableCustomPageComponent(v *string) *TournamentUpdateOne {
	if v != nil {
		_u.SetCustomPageComponent(*v)
	}
	return _u
}

// SetExternalLink sets the "external_link" field.
func (_u *TournamentUpdateOne) SetExternalLink(v string) *TournamentUpdateOne {
	_u.mutation.SetExternalLink(v)
	return _u
}

// SetNillableExternalLink sets the "external_link" field if the given value is not nil.
func (_u *TournamentUpdateOne) SetNillableExternalLink(v *string) *TournamentUpdateOne {
	if v != nil {
		_u.SetExternalLink(*v)
	}
	return _u
}

// ClearExternalLink clears the value of the "external_link" field.
func (_u *TournamentUpdateOne) ClearExternalLink() *TournamentUpdateOne {
	_u.mutation.ClearExternalLink()
	return _u
}

// SetResults sets the "results" field.
func (_u *TournamentUpdateOne) SetResults(v map[string]interface{}) *TournamentUpdateOne {
	_u.mutation.SetResults(v)
	return _u
}

// ClearResults clears the value of the "results" field.
func (_u *TournamentUpdateOne) ClearResults() *TournamentUpdateOne {
	_u.mutation.ClearResults()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TournamentUpdateOne) SetCreatedAt(v time.Time) *TournamentUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TournamentUpdateOne) SetNillableCreatedAt(v *time.Time) *TournamentUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *TournamentUpdateOne) SetCreatorID(id int) *TournamentUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *TournamentUpdateOne) SetCreator(v *User) *TournamentUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// AddAdminIDs adds the "admins" edge to the TournamentAdmin entity by IDs.
func (_u *TournamentUpdateOne) AddAdminIDs(ids ...int) *TournamentUpdateOne {
	_u.mutation.AddAdminIDs(ids...)
	return _u
}

// AddAdmins adds the "admins" edges to the TournamentAdmin entity.
func (_u *TournamentUpdateOne) AddAdmins(v ...*TournamentAdmin) *TournamentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdminIDs(ids...)
}

// AddTeamIDs adds the "teams" edge to the Team entity by IDs.
func (_u *TournamentUpdateOne) AddTeamIDs(ids ...int) *TournamentUpdateOne {
	_u.mutation.AddTeamIDs(ids...)
	return _u
}

// AddTeams adds the "teams" edges to the Team entity.
func (_u *TournamentUpdateOne) AddTeams(v ...*Team) *TournamentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamIDs(ids...)
}

// AddRankGroupIDs adds the "rank_groups" edge to the RankGroup entity by IDs.
func (_u *TournamentUpdateOne) AddRankGroupIDs(ids ...int) *TournamentUpdateOne {
	_u.mutation.AddRankGroupIDs(ids...)
	return _u
}

// AddRankGroups adds the "rank_groups" edges to the RankGroup entity.
func (_u *TournamentUpdateOne) AddRankGroups(v ...*RankGroup) *TournamentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRankGroupIDs(ids...)
}

// Mutation returns the TournamentMutation object of the builder.
func (_u *TournamentUpdateOne) Mutation() *TournamentMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *TournamentUpdateOne) ClearCreator() *TournamentUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearAdmins clears all "admins" edges to the TournamentAdmin entity.
func (_u *TournamentUpdateOne) ClearAdmins() *TournamentUpdateOne {
	_u.mutation.ClearAdmins()
	return _u
}

// RemoveAdminIDs removes the "admins" edge to TournamentAdmin entities by IDs.
func (_u *TournamentUpdateOne) RemoveAdminIDs(ids ...int) *TournamentUpdateOne {
	_u.mutation.RemoveAdminIDs(ids...)
	return _u
}

// RemoveAdmins removes "admins" edges to TournamentAdmin entities.
func (_u *TournamentUpdateOne) RemoveAdmins(v ...*TournamentAdmin) *TournamentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdminIDs(ids...)
}

// ClearTeams clears all "teams" edges to the Team entity.
func (_u *TournamentUpdateOne) ClearTeams() *TournamentUpdateOne {
	_u.mutation.ClearTeams()
	return _u
}

// RemoveTeamIDs removes the "teams" edge to Team entities by IDs.
func (_u *TournamentUpdateOne) RemoveTeamIDs(ids ...int) *TournamentUpdateOne {
	_u.mutation.RemoveTeamIDs(ids...)
	return _u
}

// RemoveTeams removes "teams" edges to Team entities.
func (_u *TournamentUpdateOne) RemoveTeams(v ...*Team) *TournamentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamIDs(ids...)
}

// ClearRankGroups clears all "rank_groups" edges to the RankGroup entity.
func (_u *TournamentUpdateOne) ClearRankGroups() *TournamentUpdateOne {
	_u.mutation.ClearRankGroups()
	return _u
}

// RemoveRankGroupIDs removes the "rank_groups" edge to RankGroup entities by IDs.
func (_u *TournamentUpdateOne) RemoveRankGroupIDs(ids ...int) *TournamentUpdateOne {
	_u.mutation.RemoveRankGroupIDs(ids...)
	return _u
}

// RemoveRankGroups removes "rank_groups" edges to RankGroup entities.
func (_u *TournamentUpdateOne) RemoveRankGroups(v ...*RankGroup) *TournamentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRankGroupIDs(ids...)
}

// Where appends a list predicates to the TournamentUpdate builder.
func (_u *TournamentUpdateOne) Where(ps ...predicate.Tournament) *TournamentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TournamentUpdateOne) Select(field string, fields ...string) *TournamentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tournament entity.
func (_u *TournamentUpdateOne) Save(ctx context.Context) (*Tournament, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TournamentUpdateOne) SaveX(ctx context.Context) *Tournament {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TournamentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TournamentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TournamentUpdateOne) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := tournament.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Tournament.state": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Tournament.creator"`)
	}
	return nil
}

func (_u *TournamentUpdateOne) sqlSave(ctx context.Context) (_node *Tournament, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tournament.Table, tournament.Columns, sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tournament.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tournament.FieldID)
		for _, f := range fields {
			if !tournament.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tournament.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(tournament.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tournament.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tournament.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsVisible(); ok {
		_spec.SetField(tournament.FieldIsVisible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RegistrationStart(); ok {
		_spec.SetField(tournament.FieldRegistrationStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RegistrationEnd(); ok {
		_spec.SetField(tournament.FieldRegistrationEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TournamentStart(); ok {
		_spec.SetField(tournament.FieldTournamentStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TournamentEnd(); ok {
		_spec.SetField(tournament.FieldTournamentEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(tournament.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MaxTeams(); ok {
		_spec.SetField(tournament.FieldMaxTeams, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTeams(); ok {
		_spec.AddField(tournament.FieldMaxTeams, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TeamStructure(); ok {
		_spec.SetField(tournament.FieldTeamStructure, field.TypeJSON, value)
	}
	if _u.mutation.TeamStructureCleared() {
		_spec.ClearField(tournament.FieldTeamStructure, field.TypeJSON)
	}
	if value, ok := _u.mutation.CustomPageComponent(); ok {
		_spec.SetField(tournament.FieldCustomPageComponent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalLink(); ok {
		_spec.SetField(tournament.FieldExternalLink, field.TypeString, value)
	}
	if _u.mutation.ExternalLinkCleared() {
		_spec.ClearField(tournament.FieldExternalLink, field.TypeString)
	}
	if value, ok := _u.mutation.Results(); ok {
		_spec.SetField(tournament.FieldResults, field.TypeJSON, value)
	}
	if _u.mutation.ResultsCleared() {
		_spec.ClearField(tournament.FieldResults, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(tournament.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tournament.CreatorTable,
			Columns: []string{tournament.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tournament.CreatorTable,
			Columns: []string{tournament.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.AdminsTable,
			Columns: []string{tournament.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournamentadmin.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdminsIDs(); len(nodes) > 0 && !_u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.AdminsTable,
			Columns: []string{tournament.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournamentadmin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.AdminsTable,
			Columns: []string{tournament.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournamentadmin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.TeamsTable,
			Columns: []string{tournament.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamsIDs(); len(nodes) > 0 && !_u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.TeamsTable,
			Columns: []string{tournament.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.TeamsTable,
			Columns: []string{tournament.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RankGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.RankGroupsTable,
			Columns: []string{tournament.RankGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankgroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRankGroupsIDs(); len(nodes) > 0 && !_u.mutation.RankGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.RankGroupsTable,
			Columns: []string{tournament.RankGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RankGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tournament.RankGroupsTable,
			Columns: []string{tournament.RankGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rankgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Tournament{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tournament.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
