// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-website/ent/tournament"
	"base-website/ent/tournamentadmin"
	"base-website/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TournamentAdminCreate is the builder for creating a TournamentAdmin entity.
type TournamentAdminCreate struct {
	config
	mutation *TournamentAdminMutation
	hooks    []Hook
}

// SetRole sets the "role" field.
func (_c *TournamentAdminCreate) SetRole(v tournamentadmin.Role) *TournamentAdminCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *TournamentAdminCreate) SetNillableRole(v *tournamentadmin.Role) *TournamentAdminCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *TournamentAdminCreate) SetUserID(id int) *TournamentAdminCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *TournamentAdminCreate) SetUser(v *User) *TournamentAdminCreate {
	return _c.SetUserID(v.ID)
}

// SetTournamentID sets the "tournament" edge to the Tournament entity by ID.
func (_c *TournamentAdminCreate) SetTournamentID(id int) *TournamentAdminCreate {
	_c.mutation.SetTournamentID(id)
	return _c
}

// SetTournament sets the "tournament" edge to the Tournament entity.
func (_c *TournamentAdminCreate) SetTournament(v *Tournament) *TournamentAdminCreate {
	return _c.SetTournamentID(v.ID)
}

// Mutation returns the TournamentAdminMutation object of the builder.
func (_c *TournamentAdminCreate) Mutation() *TournamentAdminMutation {
	return _c.mutation
}

// Save creates the TournamentAdmin in the database.
func (_c *TournamentAdminCreate) Save(ctx context.Context) (*TournamentAdmin, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TournamentAdminCreate) SaveX(ctx context.Context) *TournamentAdmin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TournamentAdminCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TournamentAdminCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TournamentAdminCreate) defaults() {
	if _, ok := _c.mutation.Role(); !ok {
		v := tournamentadmin.DefaultRole
		_c.mutation.SetRole(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TournamentAdminCreate) check() error {
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "TournamentAdmin.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := tournamentadmin.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "TournamentAdmin.role": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "TournamentAdmin.user"`)}
	}
	if len(_c.mutation.TournamentIDs()) == 0 {
		return &ValidationError{Name: "tournament", err: errors.New(`ent: missing required edge "TournamentAdmin.tournament"`)}
	}
	return nil
}

func (_c *TournamentAdminCreate) sqlSave(ctx context.Context) (*TournamentAdmin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TournamentAdminCreate) createSpec() (*TournamentAdmin, *sqlgraph.CreateSpec) {
	var (
		_node = &TournamentAdmin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tournamentadmin.Table, sqlgraph.NewFieldSpec(tournamentadmin.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(tournamentadmin.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tournamentadmin.UserTable,
			Columns: []string{tournamentadmin.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tournament_admin_user = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TournamentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tournamentadmin.TournamentTable,
			Columns: []string{tournamentadmin.TournamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tournament.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tournament_admin_tournament = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TournamentAdminCreateBulk is the builder for creating many TournamentAdmin entities in bulk.
type TournamentAdminCreateBulk struct {
	config
	err      error
	builders []*TournamentAdminCreate
}

// Save creates the TournamentAdmin entities in the database.
func (_c *TournamentAdminCreateBulk) Save(ctx context.Context) ([]*TournamentAdmin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TournamentAdmin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TournamentAdminMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TournamentAdminCreateBulk) SaveX(ctx context.Context) []*TournamentAdmin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TournamentAdminCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TournamentAdminCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
