// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-website/ent/predicate"
	"base-website/ent/tournamentadmin"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TournamentAdminDelete is the builder for deleting a TournamentAdmin entity.
type TournamentAdminDelete struct {
	config
	hooks    []Hook
	mutation *TournamentAdminMutation
}

// Where appends a list predicates to the TournamentAdminDelete builder.
func (_d *TournamentAdminDelete) Where(ps ...predicate.TournamentAdmin) *TournamentAdminDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TournamentAdminDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TournamentAdminDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TournamentAdminDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tournamentadmin.Table, sqlgraph.NewFieldSpec(tournamentadmin.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TournamentAdminDeleteOne is the builder for deleting a single TournamentAdmin entity.
type TournamentAdminDeleteOne struct {
	_d *TournamentAdminDelete
}

// Where appends a list predicates to the TournamentAdminDelete builder.
func (_d *TournamentAdminDeleteOne) Where(ps ...predicate.TournamentAdmin) *TournamentAdminDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TournamentAdminDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tournamentadmin.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TournamentAdminDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
