// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-website/ent/component"
	"base-website/ent/predicate"
	"base-website/ent/user"
	"base-website/ent/uservote"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserVoteUpdate is the builder for updating UserVote entities.
type UserVoteUpdate struct {
	config
	hooks    []Hook
	mutation *UserVoteMutation
}

// Where appends a list predicates to the UserVoteUpdate builder.
func (_u *UserVoteUpdate) Where(ps ...predicate.UserVote) *UserVoteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserVoteUpdate) SetCreatedAt(v time.Time) *UserVoteUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserVoteUpdate) SetNillableCreatedAt(v *time.Time) *UserVoteUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *UserVoteUpdate) SetUserID(id int) *UserVoteUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserVoteUpdate) SetUser(v *User) *UserVoteUpdate {
	return _u.SetUserID(v.ID)
}

// SetComponentID sets the "component" edge to the Component entity by ID.
func (_u *UserVoteUpdate) SetComponentID(id int) *UserVoteUpdate {
	_u.mutation.SetComponentID(id)
	return _u
}

// SetComponent sets the "component" edge to the Component entity.
func (_u *UserVoteUpdate) SetComponent(v *Component) *UserVoteUpdate {
	return _u.SetComponentID(v.ID)
}

// Mutation returns the UserVoteMutation object of the builder.
func (_u *UserVoteUpdate) Mutation() *UserVoteMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserVoteUpdate) ClearUser() *UserVoteUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearComponent clears the "component" edge to the Component entity.
func (_u *UserVoteUpdate) ClearComponent() *UserVoteUpdate {
	_u.mutation.ClearComponent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserVoteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserVoteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserVoteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserVoteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserVoteUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserVote.user"`)
	}
	if _u.mutation.ComponentCleared() && len(_u.mutation.ComponentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserVote.component"`)
	}
	return nil
}

func (_u *UserVoteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uservote.Table, uservote.Columns, sqlgraph.NewFieldSpec(uservote.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(uservote.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservote.UserTable,
			Columns: []string{uservote.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservote.UserTable,
			Columns: []string{uservote.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ComponentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservote.ComponentTable,
			Columns: []string{uservote.ComponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ComponentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservote.ComponentTable,
			Columns: []string{uservote.ComponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uservote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserVoteUpdateOne is the builder for updating a single UserVote entity.
type UserVoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserVoteMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserVoteUpdateOne) SetCreatedAt(v time.Time) *UserVoteUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserVoteUpdateOne) SetNillableCreatedAt(v *time.Time) *UserVoteUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *UserVoteUpdateOne) SetUserID(id int) *UserVoteUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserVoteUpdateOne) SetUser(v *User) *UserVoteUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetComponentID sets the "component" edge to the Component entity by ID.
func (_u *UserVoteUpdateOne) SetComponentID(id int) *UserVoteUpdateOne {
	_u.mutation.SetComponentID(id)
	return _u
}

// SetComponent sets the "component" edge to the Component entity.
func (_u *UserVoteUpdateOne) SetComponent(v *Component) *UserVoteUpdateOne {
	return _u.SetComponentID(v.ID)
}

// Mutation returns the UserVoteMutation object of the builder.
func (_u *UserVoteUpdateOne) Mutation() *UserVoteMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserVoteUpdateOne) ClearUser() *UserVoteUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearComponent clears the "component" edge to the Component entity.
func (_u *UserVoteUpdateOne) ClearComponent() *UserVoteUpdateOne {
	_u.mutation.ClearComponent()
	return _u
}

// Where appends a list predicates to the UserVoteUpdate builder.
func (_u *UserVoteUpdateOne) Where(ps ...predicate.UserVote) *UserVoteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserVoteUpdateOne) Select(field string, fields ...string) *UserVoteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserVote entity.
func (_u *UserVoteUpdateOne) Save(ctx context.Context) (*UserVote, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserVoteUpdateOne) SaveX(ctx context.Context) *UserVote {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserVoteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserVoteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserVoteUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserVote.user"`)
	}
	if _u.mutation.ComponentCleared() && len(_u.mutation.ComponentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserVote.component"`)
	}
	return nil
}

func (_u *UserVoteUpdateOne) sqlSave(ctx context.Context) (_node *UserVote, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uservote.Table, uservote.Columns, sqlgraph.NewFieldSpec(uservote.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserVote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uservote.FieldID)
		for _, f := range fields {
			if !uservote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != uservote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(uservote.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservote.UserTable,
			Columns: []string{uservote.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservote.UserTable,
			Columns: []string{uservote.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ComponentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservote.ComponentTable,
			Columns: []string{uservote.ComponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ComponentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   uservote.ComponentTable,
			Columns: []string{uservote.ComponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserVote{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uservote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
