/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotesIndexRouteImport } from './routes/votes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VotesVoteidIndexRouteImport } from './routes/votes/$voteid/index'
import { Route as UsersMeIndexRouteImport } from './routes/users/me/index'
import { Route as UsersUseridIndexRouteImport } from './routes/users/$userid/index'
import { Route as TournamentsTournamentidIndexRouteImport } from './routes/tournaments/$tournamentid/index'
import { Route as AuthCallbackIndexRouteImport } from './routes/auth/callback/index'
import { Route as AdminVotesIndexRouteImport } from './routes/admin/votes/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTeamsIndexRouteImport } from './routes/admin/teams/index'
import { Route as AdminAdminsIndexRouteImport } from './routes/admin/admins/index'
import { Route as VotesVoteidResultsIndexRouteImport } from './routes/votes/$voteid/results/index'
import { Route as VotesVoteidLiveIndexRouteImport } from './routes/votes/$voteid/live/index'
import { Route as TournamentsTournamentidTeamsIndexRouteImport } from './routes/tournaments/$tournamentid/teams/index'
import { Route as TournamentsTournamentidRegisterIndexRouteImport } from './routes/tournaments/$tournamentid/register/index'
import { Route as AdminVotesVoteidIndexRouteImport } from './routes/admin/votes/$voteid/index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotesIndexRoute = VotesIndexRouteImport.update({
  id: '/votes/',
  path: '/votes/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VotesVoteidIndexRoute = VotesVoteidIndexRouteImport.update({
  id: '/votes/$voteid/',
  path: '/votes/$voteid/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersMeIndexRoute = UsersMeIndexRouteImport.update({
  id: '/users/me/',
  path: '/users/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUseridIndexRoute = UsersUseridIndexRouteImport.update({
  id: '/users/$userid/',
  path: '/users/$userid/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentidIndexRoute =
  TournamentsTournamentidIndexRouteImport.update({
    id: '/tournaments/$tournamentid/',
    path: '/tournaments/$tournamentid/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthCallbackIndexRoute = AuthCallbackIndexRouteImport.update({
  id: '/auth/callback/',
  path: '/auth/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVotesIndexRoute = AdminVotesIndexRouteImport.update({
  id: '/votes/',
  path: '/votes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsIndexRoute = AdminTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsIndexRoute = AdminAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => AdminRoute,
} as any)
const VotesVoteidResultsIndexRoute = VotesVoteidResultsIndexRouteImport.update({
  id: '/votes/$voteid/results/',
  path: '/votes/$voteid/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotesVoteidLiveIndexRoute = VotesVoteidLiveIndexRouteImport.update({
  id: '/votes/$voteid/live/',
  path: '/votes/$voteid/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentidTeamsIndexRoute =
  TournamentsTournamentidTeamsIndexRouteImport.update({
    id: '/tournaments/$tournamentid/teams/',
    path: '/tournaments/$tournamentid/teams/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentidRegisterIndexRoute =
  TournamentsTournamentidRegisterIndexRouteImport.update({
    id: '/tournaments/$tournamentid/register/',
    path: '/tournaments/$tournamentid/register/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminVotesVoteidIndexRoute = AdminVotesVoteidIndexRouteImport.update({
  id: '/votes/$voteid/',
  path: '/votes/$voteid/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/users': typeof UsersIndexRoute
  '/votes': typeof VotesIndexRoute
  '/admin/admins': typeof AdminAdminsIndexRoute
  '/admin/teams': typeof AdminTeamsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/votes': typeof AdminVotesIndexRoute
  '/auth/callback': typeof AuthCallbackIndexRoute
  '/tournaments/$tournamentid': typeof TournamentsTournamentidIndexRoute
  '/users/$userid': typeof UsersUseridIndexRoute
  '/users/me': typeof UsersMeIndexRoute
  '/votes/$voteid': typeof VotesVoteidIndexRoute
  '/admin/votes/$voteid': typeof AdminVotesVoteidIndexRoute
  '/tournaments/$tournamentid/register': typeof TournamentsTournamentidRegisterIndexRoute
  '/tournaments/$tournamentid/teams': typeof TournamentsTournamentidTeamsIndexRoute
  '/votes/$voteid/live': typeof VotesVoteidLiveIndexRoute
  '/votes/$voteid/results': typeof VotesVoteidResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/users': typeof UsersIndexRoute
  '/votes': typeof VotesIndexRoute
  '/admin/admins': typeof AdminAdminsIndexRoute
  '/admin/teams': typeof AdminTeamsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/votes': typeof AdminVotesIndexRoute
  '/auth/callback': typeof AuthCallbackIndexRoute
  '/tournaments/$tournamentid': typeof TournamentsTournamentidIndexRoute
  '/users/$userid': typeof UsersUseridIndexRoute
  '/users/me': typeof UsersMeIndexRoute
  '/votes/$voteid': typeof VotesVoteidIndexRoute
  '/admin/votes/$voteid': typeof AdminVotesVoteidIndexRoute
  '/tournaments/$tournamentid/register': typeof TournamentsTournamentidRegisterIndexRoute
  '/tournaments/$tournamentid/teams': typeof TournamentsTournamentidTeamsIndexRoute
  '/votes/$voteid/live': typeof VotesVoteidLiveIndexRoute
  '/votes/$voteid/results': typeof VotesVoteidResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/votes/': typeof VotesIndexRoute
  '/admin/admins/': typeof AdminAdminsIndexRoute
  '/admin/teams/': typeof AdminTeamsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/votes/': typeof AdminVotesIndexRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/tournaments/$tournamentid/': typeof TournamentsTournamentidIndexRoute
  '/users/$userid/': typeof UsersUseridIndexRoute
  '/users/me/': typeof UsersMeIndexRoute
  '/votes/$voteid/': typeof VotesVoteidIndexRoute
  '/admin/votes/$voteid/': typeof AdminVotesVoteidIndexRoute
  '/tournaments/$tournamentid/register/': typeof TournamentsTournamentidRegisterIndexRoute
  '/tournaments/$tournamentid/teams/': typeof TournamentsTournamentidTeamsIndexRoute
  '/votes/$voteid/live/': typeof VotesVoteidLiveIndexRoute
  '/votes/$voteid/results/': typeof VotesVoteidResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/admin/'
    | '/tournaments'
    | '/users'
    | '/votes'
    | '/admin/admins'
    | '/admin/teams'
    | '/admin/users'
    | '/admin/votes'
    | '/auth/callback'
    | '/tournaments/$tournamentid'
    | '/users/$userid'
    | '/users/me'
    | '/votes/$voteid'
    | '/admin/votes/$voteid'
    | '/tournaments/$tournamentid/register'
    | '/tournaments/$tournamentid/teams'
    | '/votes/$voteid/live'
    | '/votes/$voteid/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/tournaments'
    | '/users'
    | '/votes'
    | '/admin/admins'
    | '/admin/teams'
    | '/admin/users'
    | '/admin/votes'
    | '/auth/callback'
    | '/tournaments/$tournamentid'
    | '/users/$userid'
    | '/users/me'
    | '/votes/$voteid'
    | '/admin/votes/$voteid'
    | '/tournaments/$tournamentid/register'
    | '/tournaments/$tournamentid/teams'
    | '/votes/$voteid/live'
    | '/votes/$voteid/results'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/admin/'
    | '/tournaments/'
    | '/users/'
    | '/votes/'
    | '/admin/admins/'
    | '/admin/teams/'
    | '/admin/users/'
    | '/admin/votes/'
    | '/auth/callback/'
    | '/tournaments/$tournamentid/'
    | '/users/$userid/'
    | '/users/me/'
    | '/votes/$voteid/'
    | '/admin/votes/$voteid/'
    | '/tournaments/$tournamentid/register/'
    | '/tournaments/$tournamentid/teams/'
    | '/votes/$voteid/live/'
    | '/votes/$voteid/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  VotesIndexRoute: typeof VotesIndexRoute
  AuthCallbackIndexRoute: typeof AuthCallbackIndexRoute
  TournamentsTournamentidIndexRoute: typeof TournamentsTournamentidIndexRoute
  UsersUseridIndexRoute: typeof UsersUseridIndexRoute
  UsersMeIndexRoute: typeof UsersMeIndexRoute
  VotesVoteidIndexRoute: typeof VotesVoteidIndexRoute
  TournamentsTournamentidRegisterIndexRoute: typeof TournamentsTournamentidRegisterIndexRoute
  TournamentsTournamentidTeamsIndexRoute: typeof TournamentsTournamentidTeamsIndexRoute
  VotesVoteidLiveIndexRoute: typeof VotesVoteidLiveIndexRoute
  VotesVoteidResultsIndexRoute: typeof VotesVoteidResultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votes/': {
      id: '/votes/'
      path: '/votes'
      fullPath: '/votes'
      preLoaderRoute: typeof VotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/votes/$voteid/': {
      id: '/votes/$voteid/'
      path: '/votes/$voteid'
      fullPath: '/votes/$voteid'
      preLoaderRoute: typeof VotesVoteidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/me/': {
      id: '/users/me/'
      path: '/users/me'
      fullPath: '/users/me'
      preLoaderRoute: typeof UsersMeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userid/': {
      id: '/users/$userid/'
      path: '/users/$userid'
      fullPath: '/users/$userid'
      preLoaderRoute: typeof UsersUseridIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentid/': {
      id: '/tournaments/$tournamentid/'
      path: '/tournaments/$tournamentid'
      fullPath: '/tournaments/$tournamentid'
      preLoaderRoute: typeof TournamentsTournamentidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/': {
      id: '/auth/callback/'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/votes/': {
      id: '/admin/votes/'
      path: '/votes'
      fullPath: '/admin/votes'
      preLoaderRoute: typeof AdminVotesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams/': {
      id: '/admin/teams/'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins/': {
      id: '/admin/admins/'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/votes/$voteid/results/': {
      id: '/votes/$voteid/results/'
      path: '/votes/$voteid/results'
      fullPath: '/votes/$voteid/results'
      preLoaderRoute: typeof VotesVoteidResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votes/$voteid/live/': {
      id: '/votes/$voteid/live/'
      path: '/votes/$voteid/live'
      fullPath: '/votes/$voteid/live'
      preLoaderRoute: typeof VotesVoteidLiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentid/teams/': {
      id: '/tournaments/$tournamentid/teams/'
      path: '/tournaments/$tournamentid/teams'
      fullPath: '/tournaments/$tournamentid/teams'
      preLoaderRoute: typeof TournamentsTournamentidTeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentid/register/': {
      id: '/tournaments/$tournamentid/register/'
      path: '/tournaments/$tournamentid/register'
      fullPath: '/tournaments/$tournamentid/register'
      preLoaderRoute: typeof TournamentsTournamentidRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/votes/$voteid/': {
      id: '/admin/votes/$voteid/'
      path: '/votes/$voteid'
      fullPath: '/admin/votes/$voteid'
      preLoaderRoute: typeof AdminVotesVoteidIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdminsIndexRoute: typeof AdminAdminsIndexRoute
  AdminTeamsIndexRoute: typeof AdminTeamsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminVotesIndexRoute: typeof AdminVotesIndexRoute
  AdminVotesVoteidIndexRoute: typeof AdminVotesVoteidIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAdminsIndexRoute: AdminAdminsIndexRoute,
  AdminTeamsIndexRoute: AdminTeamsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminVotesIndexRoute: AdminVotesIndexRoute,
  AdminVotesVoteidIndexRoute: AdminVotesVoteidIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  TournamentsIndexRoute: TournamentsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  VotesIndexRoute: VotesIndexRoute,
  AuthCallbackIndexRoute: AuthCallbackIndexRoute,
  TournamentsTournamentidIndexRoute: TournamentsTournamentidIndexRoute,
  UsersUseridIndexRoute: UsersUseridIndexRoute,
  UsersMeIndexRoute: UsersMeIndexRoute,
  VotesVoteidIndexRoute: VotesVoteidIndexRoute,
  TournamentsTournamentidRegisterIndexRoute:
    TournamentsTournamentidRegisterIndexRoute,
  TournamentsTournamentidTeamsIndexRoute:
    TournamentsTournamentidTeamsIndexRoute,
  VotesVoteidLiveIndexRoute: VotesVoteidLiveIndexRoute,
  VotesVoteidResultsIndexRoute: VotesVoteidResultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
