/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotesIndexRouteImport } from './routes/votes/index'
import { Route as TournamentIndexRouteImport } from './routes/tournament/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VotesVoteidIndexRouteImport } from './routes/votes/$voteid/index'
import { Route as AuthCallbackIndexRouteImport } from './routes/auth/callback/index'
import { Route as AdminVotesIndexRouteImport } from './routes/admin/votes/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTeamsIndexRouteImport } from './routes/admin/teams/index'
import { Route as AdminAdminsIndexRouteImport } from './routes/admin/admins/index'
import { Route as VotesVoteidResultsIndexRouteImport } from './routes/votes/$voteid/results/index'
import { Route as VotesVoteidLiveIndexRouteImport } from './routes/votes/$voteid/live/index'
import { Route as AdminVotesVoteidIndexRouteImport } from './routes/admin/votes/$voteid/index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotesIndexRoute = VotesIndexRouteImport.update({
  id: '/votes/',
  path: '/votes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentIndexRoute = TournamentIndexRouteImport.update({
  id: '/tournament/',
  path: '/tournament/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VotesVoteidIndexRoute = VotesVoteidIndexRouteImport.update({
  id: '/votes/$voteid/',
  path: '/votes/$voteid/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackIndexRoute = AuthCallbackIndexRouteImport.update({
  id: '/auth/callback/',
  path: '/auth/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVotesIndexRoute = AdminVotesIndexRouteImport.update({
  id: '/votes/',
  path: '/votes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsIndexRoute = AdminTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsIndexRoute = AdminAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => AdminRoute,
} as any)
const VotesVoteidResultsIndexRoute = VotesVoteidResultsIndexRouteImport.update({
  id: '/votes/$voteid/results/',
  path: '/votes/$voteid/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotesVoteidLiveIndexRoute = VotesVoteidLiveIndexRouteImport.update({
  id: '/votes/$voteid/live/',
  path: '/votes/$voteid/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVotesVoteidIndexRoute = AdminVotesVoteidIndexRouteImport.update({
  id: '/votes/$voteid/',
  path: '/votes/$voteid/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/tournament': typeof TournamentIndexRoute
  '/votes': typeof VotesIndexRoute
  '/admin/admins': typeof AdminAdminsIndexRoute
  '/admin/teams': typeof AdminTeamsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/votes': typeof AdminVotesIndexRoute
  '/auth/callback': typeof AuthCallbackIndexRoute
  '/votes/$voteid': typeof VotesVoteidIndexRoute
  '/admin/votes/$voteid': typeof AdminVotesVoteidIndexRoute
  '/votes/$voteid/live': typeof VotesVoteidLiveIndexRoute
  '/votes/$voteid/results': typeof VotesVoteidResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminIndexRoute
  '/tournament': typeof TournamentIndexRoute
  '/votes': typeof VotesIndexRoute
  '/admin/admins': typeof AdminAdminsIndexRoute
  '/admin/teams': typeof AdminTeamsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/votes': typeof AdminVotesIndexRoute
  '/auth/callback': typeof AuthCallbackIndexRoute
  '/votes/$voteid': typeof VotesVoteidIndexRoute
  '/admin/votes/$voteid': typeof AdminVotesVoteidIndexRoute
  '/votes/$voteid/live': typeof VotesVoteidLiveIndexRoute
  '/votes/$voteid/results': typeof VotesVoteidResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/tournament/': typeof TournamentIndexRoute
  '/votes/': typeof VotesIndexRoute
  '/admin/admins/': typeof AdminAdminsIndexRoute
  '/admin/teams/': typeof AdminTeamsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/votes/': typeof AdminVotesIndexRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/votes/$voteid/': typeof VotesVoteidIndexRoute
  '/admin/votes/$voteid/': typeof AdminVotesVoteidIndexRoute
  '/votes/$voteid/live/': typeof VotesVoteidLiveIndexRoute
  '/votes/$voteid/results/': typeof VotesVoteidResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/admin/'
    | '/tournament'
    | '/votes'
    | '/admin/admins'
    | '/admin/teams'
    | '/admin/users'
    | '/admin/votes'
    | '/auth/callback'
    | '/votes/$voteid'
    | '/admin/votes/$voteid'
    | '/votes/$voteid/live'
    | '/votes/$voteid/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/tournament'
    | '/votes'
    | '/admin/admins'
    | '/admin/teams'
    | '/admin/users'
    | '/admin/votes'
    | '/auth/callback'
    | '/votes/$voteid'
    | '/admin/votes/$voteid'
    | '/votes/$voteid/live'
    | '/votes/$voteid/results'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/admin/'
    | '/tournament/'
    | '/votes/'
    | '/admin/admins/'
    | '/admin/teams/'
    | '/admin/users/'
    | '/admin/votes/'
    | '/auth/callback/'
    | '/votes/$voteid/'
    | '/admin/votes/$voteid/'
    | '/votes/$voteid/live/'
    | '/votes/$voteid/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  TournamentIndexRoute: typeof TournamentIndexRoute
  VotesIndexRoute: typeof VotesIndexRoute
  AuthCallbackIndexRoute: typeof AuthCallbackIndexRoute
  VotesVoteidIndexRoute: typeof VotesVoteidIndexRoute
  VotesVoteidLiveIndexRoute: typeof VotesVoteidLiveIndexRoute
  VotesVoteidResultsIndexRoute: typeof VotesVoteidResultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votes/': {
      id: '/votes/'
      path: '/votes'
      fullPath: '/votes'
      preLoaderRoute: typeof VotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/': {
      id: '/tournament/'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/votes/$voteid/': {
      id: '/votes/$voteid/'
      path: '/votes/$voteid'
      fullPath: '/votes/$voteid'
      preLoaderRoute: typeof VotesVoteidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/': {
      id: '/auth/callback/'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/votes/': {
      id: '/admin/votes/'
      path: '/votes'
      fullPath: '/admin/votes'
      preLoaderRoute: typeof AdminVotesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams/': {
      id: '/admin/teams/'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins/': {
      id: '/admin/admins/'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/votes/$voteid/results/': {
      id: '/votes/$voteid/results/'
      path: '/votes/$voteid/results'
      fullPath: '/votes/$voteid/results'
      preLoaderRoute: typeof VotesVoteidResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votes/$voteid/live/': {
      id: '/votes/$voteid/live/'
      path: '/votes/$voteid/live'
      fullPath: '/votes/$voteid/live'
      preLoaderRoute: typeof VotesVoteidLiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/votes/$voteid/': {
      id: '/admin/votes/$voteid/'
      path: '/votes/$voteid'
      fullPath: '/admin/votes/$voteid'
      preLoaderRoute: typeof AdminVotesVoteidIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdminsIndexRoute: typeof AdminAdminsIndexRoute
  AdminTeamsIndexRoute: typeof AdminTeamsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminVotesIndexRoute: typeof AdminVotesIndexRoute
  AdminVotesVoteidIndexRoute: typeof AdminVotesVoteidIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAdminsIndexRoute: AdminAdminsIndexRoute,
  AdminTeamsIndexRoute: AdminTeamsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminVotesIndexRoute: AdminVotesIndexRoute,
  AdminVotesVoteidIndexRoute: AdminVotesVoteidIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  TournamentIndexRoute: TournamentIndexRoute,
  VotesIndexRoute: VotesIndexRoute,
  AuthCallbackIndexRoute: AuthCallbackIndexRoute,
  VotesVoteidIndexRoute: VotesVoteidIndexRoute,
  VotesVoteidLiveIndexRoute: VotesVoteidLiveIndexRoute,
  VotesVoteidResultsIndexRoute: VotesVoteidResultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
