-- Create "apps" table
CREATE TABLE "apps" (
  "id" character varying NOT NULL,
  "secret" character varying NOT NULL,
  "name" character varying NOT NULL,
  "redirect_uris" jsonb NOT NULL,
  "implicit_consent" boolean NOT NULL,
  "description" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "last_login_at" timestamptz NULL,
  "roles" jsonb NOT NULL,
  "owner_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "apps_users_apps" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "consents" table
CREATE TABLE "consents" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "scopes" jsonb NOT NULL,
  "expiration_date" timestamptz NOT NULL,
  "application_id" character varying NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "consents_apps_consents" FOREIGN KEY ("application_id") REFERENCES "apps" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "consents_users_consents" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
