-- Create "auth_codes" table
CREATE TABLE "auth_codes" (
  "id" character varying NOT NULL,
  "auth_request_id" character varying NOT NULL,
  "expiration" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "auth_refresh_tokens" table
CREATE TABLE "auth_refresh_tokens" (
  "id" character varying NOT NULL,
  "token" character varying NOT NULL,
  "subject" character varying NOT NULL,
  "auth_time" timestamptz NOT NULL,
  "amr" jsonb NOT NULL,
  "audience" jsonb NOT NULL,
  "user_id" character varying NOT NULL,
  "application_id" character varying NOT NULL,
  "expiration" timestamptz NOT NULL,
  "scopes" jsonb NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "auth_tokens" table
CREATE TABLE "auth_tokens" (
  "id" character varying NOT NULL,
  "application_id" character varying NOT NULL,
  "subject" character varying NOT NULL,
  "refresh_token_id" character varying NOT NULL,
  "audience" jsonb NOT NULL,
  "expiration" timestamptz NOT NULL,
  "scopes" jsonb NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "users" table
CREATE TABLE "users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" character varying NOT NULL,
  "first_name" character varying NOT NULL,
  "last_name" character varying NOT NULL,
  "email" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "picture" character varying NULL,
  "kind" character varying NOT NULL DEFAULT 'user',
  "usual_full_name" character varying NOT NULL,
  "usual_first_name" character varying NULL,
  "roles" jsonb NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");
-- Create "votes" table
CREATE TABLE "votes" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "description" character varying NULL,
  "visible" boolean NOT NULL DEFAULT false,
  "start_at" timestamptz NOT NULL,
  "end_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "user_created_votes" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "votes_users_created_votes" FOREIGN KEY ("user_created_votes") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "components" table
CREATE TABLE "components" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "description" character varying NULL,
  "image_url" character varying NULL,
  "color" character varying NULL,
  "vote_components" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "components_votes_components" FOREIGN KEY ("vote_components") REFERENCES "votes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "user_votes" table
CREATE TABLE "user_votes" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "component_user_votes" bigint NOT NULL,
  "user_user_votes" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_votes_components_user_votes" FOREIGN KEY ("component_user_votes") REFERENCES "components" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "user_votes_users_user_votes" FOREIGN KEY ("user_user_votes") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
