-- Create "auth_codes" table
CREATE TABLE "auth_codes" (
  "id" character varying NOT NULL,
  "auth_request_id" character varying NOT NULL,
  "expiration" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "auth_refresh_tokens" table
CREATE TABLE "auth_refresh_tokens" (
  "id" character varying NOT NULL,
  "token" character varying NOT NULL,
  "subject" character varying NOT NULL,
  "auth_time" timestamptz NOT NULL,
  "amr" jsonb NOT NULL,
  "audience" jsonb NOT NULL,
  "user_id" character varying NOT NULL,
  "application_id" character varying NOT NULL,
  "expiration" timestamptz NOT NULL,
  "scopes" jsonb NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "auth_tokens" table
CREATE TABLE "auth_tokens" (
  "id" character varying NOT NULL,
  "application_id" character varying NOT NULL,
  "subject" character varying NOT NULL,
  "refresh_token_id" character varying NOT NULL,
  "audience" jsonb NOT NULL,
  "expiration" timestamptz NOT NULL,
  "scopes" jsonb NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "users" table
CREATE TABLE "users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" character varying NOT NULL,
  "email" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "anonymized_at" timestamptz NULL,
  "intra_id" bigint NULL,
  "picture" character varying NULL,
  "kind" character varying NOT NULL DEFAULT 'user',
  "roles" jsonb NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "users_intra_id_key" to table: "users"
CREATE UNIQUE INDEX "users_intra_id_key" ON "users" ("intra_id");
-- Create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");
-- Create "apps" table
CREATE TABLE "apps" (
  "id" character varying NOT NULL,
  "secret" character varying NOT NULL,
  "name" character varying NOT NULL,
  "redirect_uris" jsonb NOT NULL,
  "implicit_consent" boolean NOT NULL,
  "description" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "last_login_at" timestamptz NULL,
  "roles" jsonb NOT NULL,
  "owner_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "apps_users_apps" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "votes" table
CREATE TABLE "votes" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "description" character varying NULL,
  "visible" boolean NOT NULL DEFAULT false,
  "start_at" timestamptz NOT NULL,
  "end_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "user_created_votes" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "votes_users_created_votes" FOREIGN KEY ("user_created_votes") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "components" table
CREATE TABLE "components" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "description" character varying NULL,
  "image_url" character varying NULL,
  "color" character varying NULL,
  "vote_components" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "components_votes_components" FOREIGN KEY ("vote_components") REFERENCES "votes" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "consents" table
CREATE TABLE "consents" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "scopes" jsonb NOT NULL,
  "expiration_date" timestamptz NOT NULL,
  "application_id" character varying NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "consents_apps_consents" FOREIGN KEY ("application_id") REFERENCES "apps" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "consents_users_consents" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "tournaments" table
CREATE TABLE "tournaments" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "slug" character varying NOT NULL,
  "name" character varying NOT NULL,
  "description" character varying NOT NULL,
  "image_url" character varying NULL,
  "is_visible" boolean NOT NULL DEFAULT false,
  "registration_start" timestamptz NOT NULL,
  "registration_end" timestamptz NOT NULL,
  "tournament_start" timestamptz NOT NULL,
  "tournament_end" timestamptz NULL,
  "max_teams" bigint NOT NULL,
  "team_structure" jsonb NULL,
  "custom_page_component" character varying NOT NULL DEFAULT 'default',
  "external_links" jsonb NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "user_created_tournaments" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "tournaments_users_created_tournaments" FOREIGN KEY ("user_created_tournaments") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "tournaments_slug_key" to table: "tournaments"
CREATE UNIQUE INDEX "tournaments_slug_key" ON "tournaments" ("slug");
-- Create "rank_groups" table
CREATE TABLE "rank_groups" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "rank_min" bigint NOT NULL,
  "rank_max" bigint NOT NULL,
  "position" bigint NOT NULL,
  "tournament_rank_groups" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "rank_groups_tournaments_rank_groups" FOREIGN KEY ("tournament_rank_groups") REFERENCES "tournaments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "rankgroup_position_tournament_rank_groups" to table: "rank_groups"
CREATE UNIQUE INDEX "rankgroup_position_tournament_rank_groups" ON "rank_groups" ("position", "tournament_rank_groups");
-- Create "teams" table
CREATE TABLE "teams" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "image_url" character varying NULL,
  "status" character varying NOT NULL DEFAULT 'DRAFT',
  "is_locked" boolean NOT NULL DEFAULT false,
  "queue_position" bigint NULL,
  "score" bigint NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "rank_group_teams" bigint NULL,
  "tournament_teams" bigint NOT NULL,
  "user_created_teams" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "teams_rank_groups_teams" FOREIGN KEY ("rank_group_teams") REFERENCES "rank_groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "teams_tournaments_teams" FOREIGN KEY ("tournament_teams") REFERENCES "tournaments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "teams_users_created_teams" FOREIGN KEY ("user_created_teams") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "team_user_created_teams_tournament_teams" to table: "teams"
CREATE UNIQUE INDEX "team_user_created_teams_tournament_teams" ON "teams" ("user_created_teams", "tournament_teams");
-- Create "invitations" table
CREATE TABLE "invitations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "message" character varying NULL,
  "role" character varying NOT NULL,
  "team_invitations" bigint NOT NULL,
  "user_received_invitations" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "invitations_teams_invitations" FOREIGN KEY ("team_invitations") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "invitations_users_received_invitations" FOREIGN KEY ("user_received_invitations") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "invitation_team_invitations_user_received_invitations" to table: "invitations"
CREATE UNIQUE INDEX "invitation_team_invitations_user_received_invitations" ON "invitations" ("team_invitations", "user_received_invitations");
-- Create "team_members" table
CREATE TABLE "team_members" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "role" character varying NOT NULL,
  "team_members" bigint NOT NULL,
  "tournament_team_members" bigint NOT NULL,
  "user_team_memberships" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "team_members_teams_members" FOREIGN KEY ("team_members") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "team_members_tournaments_team_members" FOREIGN KEY ("tournament_team_members") REFERENCES "tournaments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "team_members_users_team_memberships" FOREIGN KEY ("user_team_memberships") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "teammember_user_team_memberships_team_members" to table: "team_members"
CREATE UNIQUE INDEX "teammember_user_team_memberships_team_members" ON "team_members" ("user_team_memberships", "team_members");
-- Create index "teammember_user_team_memberships_tournament_team_members" to table: "team_members"
CREATE UNIQUE INDEX "teammember_user_team_memberships_tournament_team_members" ON "team_members" ("user_team_memberships", "tournament_team_members");
-- Create "tournament_admins" table
CREATE TABLE "tournament_admins" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "role" character varying NOT NULL DEFAULT 'ADMIN',
  "tournament_admins" bigint NOT NULL,
  "user_tournament_admins" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "tournament_admins_tournaments_admins" FOREIGN KEY ("tournament_admins") REFERENCES "tournaments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "tournament_admins_users_tournament_admins" FOREIGN KEY ("user_tournament_admins") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "tournamentadmin_user_tournament_admins_tournament_admins" to table: "tournament_admins"
CREATE UNIQUE INDEX "tournamentadmin_user_tournament_admins_tournament_admins" ON "tournament_admins" ("user_tournament_admins", "tournament_admins");
-- Create "user_votes" table
CREATE TABLE "user_votes" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "component_user_votes" bigint NOT NULL,
  "user_user_votes" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_votes_components_user_votes" FOREIGN KEY ("component_user_votes") REFERENCES "components" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "user_votes_users_user_votes" FOREIGN KEY ("user_user_votes") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "uservote_user_user_votes_component_user_votes" to table: "user_votes"
CREATE UNIQUE INDEX "uservote_user_user_votes_component_user_votes" ON "user_votes" ("user_user_votes", "component_user_votes");
