-- Create "auth_codes" table
CREATE TABLE "auth_codes" (
  "id" character varying NOT NULL,
  "auth_request_id" character varying NOT NULL,
  "expiration" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "auth_refresh_tokens" table
CREATE TABLE "auth_refresh_tokens" (
  "id" character varying NOT NULL,
  "token" character varying NOT NULL,
  "subject" character varying NOT NULL,
  "auth_time" timestamptz NOT NULL,
  "amr" jsonb NOT NULL,
  "audience" jsonb NOT NULL,
  "user_id" character varying NOT NULL,
  "application_id" character varying NOT NULL,
  "expiration" timestamptz NOT NULL,
  "scopes" jsonb NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "auth_tokens" table
CREATE TABLE "auth_tokens" (
  "id" character varying NOT NULL,
  "application_id" character varying NOT NULL,
  "subject" character varying NOT NULL,
  "refresh_token_id" character varying NOT NULL,
  "audience" jsonb NOT NULL,
  "expiration" timestamptz NOT NULL,
  "scopes" jsonb NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "users" table
CREATE TABLE "users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" character varying NOT NULL,
  "email" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "anonymized_at" timestamptz NULL,
  "intra_id" bigint NULL,
  "picture" character varying NULL,
  "kind" character varying NOT NULL DEFAULT 'user',
  "roles" jsonb NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "users_intra_id_key" to table: "users"
CREATE UNIQUE INDEX "users_intra_id_key" ON "users" ("intra_id");
-- Create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");
-- Create "apps" table
CREATE TABLE "apps" (
  "id" character varying NOT NULL,
  "secret" character varying NOT NULL,
  "name" character varying NOT NULL,
  "redirect_uris" jsonb NOT NULL,
  "implicit_consent" boolean NOT NULL,
  "description" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "last_login_at" timestamptz NULL,
  "roles" jsonb NOT NULL,
  "owner_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "apps_users_owner" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "votes" table
CREATE TABLE "votes" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "description" character varying NULL,
  "visible" boolean NOT NULL DEFAULT false,
  "start_at" timestamptz NOT NULL,
  "end_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "vote_creator" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "votes_users_creator" FOREIGN KEY ("vote_creator") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "components" table
CREATE TABLE "components" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "description" character varying NULL,
  "image_url" character varying NOT NULL DEFAULT 'components/default.png',
  "color" character varying NULL,
  "component_vote" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "components_votes_vote" FOREIGN KEY ("component_vote") REFERENCES "votes" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "consents" table
CREATE TABLE "consents" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "scopes" jsonb NOT NULL,
  "expiration_date" timestamptz NOT NULL,
  "application_id" character varying NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "consents_apps_application" FOREIGN KEY ("application_id") REFERENCES "apps" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "consents_users_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "tournaments" table
CREATE TABLE "tournaments" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "slug" character varying NOT NULL,
  "name" character varying NOT NULL,
  "description" character varying NOT NULL,
  "is_visible" boolean NOT NULL DEFAULT false,
  "registration_start" timestamptz NOT NULL,
  "registration_end" timestamptz NOT NULL,
  "tournament_start" timestamptz NOT NULL,
  "tournament_end" timestamptz NULL,
  "state" character varying NOT NULL DEFAULT 'DRAFT',
  "max_teams" bigint NOT NULL,
  "team_structure" jsonb NULL,
  "custom_page_component" character varying NOT NULL DEFAULT 'default',
  "external_links" jsonb NULL,
  "created_at" timestamptz NOT NULL,
  "tournament_creator" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "tournaments_users_creator" FOREIGN KEY ("tournament_creator") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "tournaments_slug_key" to table: "tournaments"
CREATE UNIQUE INDEX "tournaments_slug_key" ON "tournaments" ("slug");
-- Create "rank_groups" table
CREATE TABLE "rank_groups" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "rank_min" bigint NOT NULL,
  "rank_max" bigint NOT NULL,
  "position" bigint NOT NULL,
  "rank_group_tournament" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "rank_groups_tournaments_tournament" FOREIGN KEY ("rank_group_tournament") REFERENCES "tournaments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "rankgroup_position_rank_group_tournament" to table: "rank_groups"
CREATE UNIQUE INDEX "rankgroup_position_rank_group_tournament" ON "rank_groups" ("position", "rank_group_tournament");
-- Create "teams" table
CREATE TABLE "teams" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "image_url" character varying NOT NULL DEFAULT 'teams/default.png',
  "status" character varying NOT NULL DEFAULT 'DRAFT',
  "is_locked" boolean NOT NULL DEFAULT false,
  "queue_position" bigint NULL,
  "score" bigint NULL,
  "created_at" timestamptz NOT NULL,
  "team_tournament" bigint NOT NULL,
  "team_creator" bigint NOT NULL,
  "team_rank_group" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "teams_rank_groups_rank_group" FOREIGN KEY ("team_rank_group") REFERENCES "rank_groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "teams_tournaments_tournament" FOREIGN KEY ("team_tournament") REFERENCES "tournaments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "teams_users_creator" FOREIGN KEY ("team_creator") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "invitations" table
CREATE TABLE "invitations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "status" character varying NOT NULL DEFAULT 'PENDING',
  "created_at" timestamptz NOT NULL,
  "expires_at" timestamptz NULL,
  "message" character varying NULL,
  "invitation_team" bigint NOT NULL,
  "invitation_invitee" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "invitations_teams_team" FOREIGN KEY ("invitation_team") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "invitations_users_invitee" FOREIGN KEY ("invitation_invitee") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "team_members" table
CREATE TABLE "team_members" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "role" character varying NOT NULL,
  "team_member_user" bigint NOT NULL,
  "team_member_team" bigint NOT NULL,
  "team_member_tournament" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "team_members_teams_team" FOREIGN KEY ("team_member_team") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "team_members_tournaments_tournament" FOREIGN KEY ("team_member_tournament") REFERENCES "tournaments" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "team_members_users_user" FOREIGN KEY ("team_member_user") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "teammember_team_member_tournament" to table: "team_members"
CREATE UNIQUE INDEX "teammember_team_member_tournament" ON "team_members" ("team_member_tournament");
-- Create "tournament_admins" table
CREATE TABLE "tournament_admins" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "role" character varying NOT NULL DEFAULT 'ADMIN',
  "tournament_admin_user" bigint NOT NULL,
  "tournament_admin_tournament" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "tournament_admins_tournaments_tournament" FOREIGN KEY ("tournament_admin_tournament") REFERENCES "tournaments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "tournament_admins_users_user" FOREIGN KEY ("tournament_admin_user") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "user_votes" table
CREATE TABLE "user_votes" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "user_vote_user" bigint NOT NULL,
  "user_vote_component" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_votes_components_component" FOREIGN KEY ("user_vote_component") REFERENCES "components" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "user_votes_users_user" FOREIGN KEY ("user_vote_user") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
