-- Create "auth_codes" table
CREATE TABLE "auth_codes" (
  "id" character varying NOT NULL,
  "auth_request_id" character varying NOT NULL,
  "expiration" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "auth_refresh_tokens" table
CREATE TABLE "auth_refresh_tokens" (
  "id" character varying NOT NULL,
  "token" character varying NOT NULL,
  "subject" character varying NOT NULL,
  "auth_time" timestamptz NOT NULL,
  "amr" jsonb NOT NULL,
  "audience" jsonb NOT NULL,
  "user_id" character varying NOT NULL,
  "application_id" character varying NOT NULL,
  "expiration" timestamptz NOT NULL,
  "scopes" jsonb NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "auth_tokens" table
CREATE TABLE "auth_tokens" (
  "id" character varying NOT NULL,
  "application_id" character varying NOT NULL,
  "subject" character varying NOT NULL,
  "refresh_token_id" character varying NOT NULL,
  "audience" jsonb NOT NULL,
  "expiration" timestamptz NOT NULL,
  "scopes" jsonb NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "users" table
CREATE TABLE "users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" character varying NOT NULL,
  "first_name" character varying NOT NULL,
  "last_name" character varying NOT NULL,
  "email" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "picture" character varying NULL,
  "kind" character varying NOT NULL DEFAULT 'user',
  "usual_full_name" character varying NOT NULL,
  "usual_first_name" character varying NULL,
  "roles" jsonb NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");
