name: Test frontend build for PRs

on:
    pull_request:
        branches:
            - main
            - dev
        paths:
            - 'frontend/**'
            - '.github/workflows/frontend-build.yaml'

jobs:
    frontend-build-test:
        name: Test frontend build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '23'
                  cache: 'pnpm'
                  cache-dependency-path: 'frontend/pnpm-lock.yaml'

            - name: Enable pnpm
              run: corepack enable

            - name: Prepare pnpm via corepack
              run: corepack prepare pnpm@latest --activate

            - name: Install frontend dependencies
              working-directory: ./frontend
              run: pnpm install --frozen-lockfile

            - name: Build frontend
              working-directory: ./frontend
              run: pnpm run build

            - name: Check build output
              working-directory: ./frontend
              run: |
                  echo "✅ Frontend build completed successfully"
                  ls -la dist/
                  echo "Build artifacts created:"
                  find dist/ -type f -name "*.js" -o -name "*.css" -o -name "*.html" | head -10

    lint-and-type-check:
        name: Lint and type check frontend
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '23'
                  cache: 'pnpm'
                  cache-dependency-path: 'frontend/pnpm-lock.yaml'

            - name: Enable pnpm
              run: corepack enable

            - name: Prepare pnpm via corepack
              run: corepack prepare pnpm@latest --activate

            - name: Install frontend dependencies
              working-directory: ./frontend
              run: pnpm install --frozen-lockfile

            - name: Run linting
              working-directory: ./frontend
              run: pnpm run lint || echo "⚠️ Linting not configured or failed"

            - name: Run type checking
              working-directory: ./frontend
              run: pnpm run type-check || echo "⚠️ Type checking not configured or failed"
