name: Test frontend build for PRs

on:
    pull_request:
        branches:
            - main
            - dev
        paths:
            - 'frontend/**'
            - '.github/workflows/frontend-build.yaml'

jobs:
    frontend-build-test:
        name: Test frontend build
        runs-on: ubuntu-latest
        env:
            WORKING_DIR: ./frontend
        defaults:
            run:
                working-directory: ${{ env.WORKING_DIR }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 23
                  cache: 'pnpm'
                  cache-dependency-path: ${{ env.WORKING_DIR }}/pnpm-lock.yaml

            - name: Install pnpm
              run: npm install -g pnpm@9

            - name: Install dependencies
              run: pnpm install --prod --frozen-lockfile

            - name: Build project
              run: pnpm build

            - name: Check build output
              run: |
                  echo "✅ Frontend build completed successfully"
                  ls -la dist/
                  echo "Build artifacts created:"
                  find dist/ -type f -name "*.js" -o -name "*.css" -o -name "*.html" | head -10

            - name: Run type checking
              run: pnpm run type-check || echo "⚠️ Type checking not configured or failed"
